import { CharacterBeamOverrides } from "../../types";

export const GokuSSJ_Beams: Record<string, CharacterBeamOverrides> = {
    "CHAVE_BEAM_45": {
        "start": {
            "imageUrl": "/Assets/especiais/beans/1/1.gif",
            "frames": 2,
            "frameWidth": 81,
            "frameHeight": 99,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -112,
            "offsetY": -211,
            "originX": 110,
            "originY": 222,
            "centerX": -8,
            "centerY": 120,
            "beamSpacing": -2
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/1/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -4,
            "offsetY": 8,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "beamSpacing": -2
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/1/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 56,
            "centerY": 172,
            "centerX": 298,
            "fullScreen": false,
            "beamSpacing": -2
        }
    },
    "CHAVE_BEAM_47": {
        "start": {
            "imageUrl": "/Assets/especiais/beans/7/1.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -110,
            "offsetY": -298,
            "originX": 110,
            "originY": 222,
            "centerX": -8,
            "centerY": 120,
            "scale": 3.25,
            "beamSpacing": -23
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/7/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -2,
            "offsetY": 1,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "scale": 3.25,
            "beamSpacing": -23
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/7/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": -52,
            "centerY": 172,
            "centerX": 298,
            "fullScreen": false,
            "scale": 3.25,
            "beamSpacing": -23
        }
    },
    "CHAVE_BEAM_48": {
        "start": {
            "imageUrl": "/Assets/especiais/beans/1/1.gif",
            "frames": 2,
            "frameWidth": 81,
            "frameHeight": 99,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -127,
            "offsetY": -282,
            "originX": 110,
            "originY": 222,
            "centerX": -8,
            "centerY": 120,
            "scale": 3.65,
            "rotation": -40,
            "beamSpacing": -2
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/1/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": -3,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "scale": 3.65,
            "rotation": -40,
            "beamSpacing": -2
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/1/3.gif",
            "frames": 2,
            "frameWidth": 62,
            "frameHeight": 101,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": -18,
            "centerY": 172,
            "centerX": 298,
            "fullScreen": false,
            "scale": 3.65,
            "beamSpacing": -2
        }
    },
};
