import { CharacterBeamOverrides } from "../../types";

export const GokuBlue_Beams: Record<string, CharacterBeamOverrides> = {
    "CHAVE_BEAM_51": {
        "start": {
            "imageUrl": "/Assets/especiais/beans/1/1.gif",
            "frames": 2,
            "frameWidth": 81,
            "frameHeight": 99,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -110,
            "offsetY": -236,
            "originX": 110,
            "originY": 222,
            "centerX": -8,
            "centerY": 120,
            "beamSpacing": -26
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/1/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": -10,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "beamSpacing": -26
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/1/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 24,
            "centerY": 172,
            "centerX": 298,
            "fullScreen": false,
            "beamSpacing": -26
        }
    },
    "CHAVE_BEAM_004": {
        "start": {
            "imageUrl": "/Assets/especiais/beans/7/1.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -110,
            "offsetY": -237,
            "originX": 110,
            "originY": 222,
            "centerX": -8,
            "centerY": 120,
            "beamSpacing": -22
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/7/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": -2,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "beamSpacing": -22
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/7/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 25,
            "centerY": 172,
            "centerX": 298,
            "beamSpacing": -22
        }
    },
    "CHAVE_BEAM_52": {
        "start": {
            "imageUrl": "/Assets/especiais/beans/9/1.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -119,
            "offsetY": -187,
            "originX": 110,
            "originY": 222,
            "centerX": -8,
            "centerY": 120
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/9/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 0,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/9/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 116,
            "centerY": 172,
            "centerX": 298
        }
    },
    "CHAVE_BEAM_53": {
        "start": {
            "imageUrl": "/Assets/especiais/beans/1/1.gif",
            "frames": 2,
            "frameWidth": 81,
            "frameHeight": 99,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -119,
            "offsetY": -211,
            "originX": 110,
            "originY": 222,
            "centerX": -8,
            "centerY": 120
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/1/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 0,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/1/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 55,
            "centerY": 172,
            "centerX": 298,
            "fullScreen": false
        }
    }
};
