import { CharacterBeamOverrides } from "../../types";

export const Kuririn_Beams: Record<string, CharacterBeamOverrides> = {
    "CHAVE_BEAM_006": {
        "id": "CHAVE_BEAM_006",
        "name": "Beam 1",
        "color": "#ffffff",
        "start": {
            "imageUrl": "/Assets/especiais/beans/1/1.gif",
            "frames": 2,
            "frameWidth": 81,
            "frameHeight": 99,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -119,
            "offsetY": -210,
            "originX": 110,
            "originY": 222,
            "centerX": -8,
            "centerY": 120,
            "beamSpacing": -2
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/1/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 3,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "beamSpacing": -2
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/1/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 56,
            "centerY": 172,
            "centerX": 298,
            "fullScreen": false,
            "beamSpacing": -2
        },
        "ownerCharacterId": "kuririn",
        "ownerAnimationKey": "Especial_1_2",
        "ownerCharacterName": "KURIRIN",
        "configKey": "CHAVE_BEAM_006",
        "baseBeamId": "CHAVE_BEAM_006"
    } as any,
    "CHAVE_BEAM_008": {
        "id": "CHAVE_BEAM_008",
        "name": "Beam 4",
        "color": "#ffffff",
        "start": {
            "imageUrl": "/Assets/especiais/beans/4/1.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -119,
            "offsetY": -191,
            "originX": 110,
            "originY": 222,
            "centerX": -8,
            "centerY": 120,
            "beamSpacing": -2
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/4/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 3,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "beamSpacing": -2
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/4/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 77,
            "centerY": 172,
            "centerX": 298,
            "fullScreen": false,
            "beamSpacing": -2
        },
        "beamHueRotate": 199,
        "beamContrast": 3,
        "beamSaturate": 2.75,
        "beamBrightness": 0.85,
        "beamOpacity": 1,
        "ownerCharacterId": "kuririn",
        "ownerAnimationKey": "Ultimate_2_3",
        "ownerCharacterName": "KURIRIN",
        "configKey": "CHAVE_BEAM_008",
        "baseBeamId": "CHAVE_BEAM_008"
    } as any,
    "CHAVE_BEAM_003": {
        "id": "CHAVE_BEAM_003",
        "name": "Beam 10",
        "start": {
            "imageUrl": "/Assets/especiais/beans/10/1.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -114,
            "offsetY": -317,
            "originX": 110,
            "originY": 222,
            "centerX": -8,
            "centerY": 120,
            "scale": 3.15,
            "beamSpacing": -33
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/10/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 2,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "scale": 3.15,
            "beamSpacing": -33
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/10/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": -44,
            "centerY": 172,
            "centerX": 298,
            "scale": 3.15,
            "beamSpacing": -33
        },
        "ownerCharacterId": "kuririn",
        "ownerAnimationKey": "Ultimate_combinado_9",
        "ownerCharacterName": "KURIRIN",
        "configKey": "CHAVE_BEAM_003",
        "baseBeamId": "CHAVE_BEAM_003"
    } as any
};
