import { CharacterBeamOverrides } from "../../types";

export const TeenGohanSSJ2_Beams: Record<string, CharacterBeamOverrides> = {
    "CHAVE_BEAM_039": {
        "start": {
            "imageUrl": "/Assets/especiais/beans/1/1.gif",
            "frames": 2,
            "frameWidth": 81,
            "frameHeight": 99,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -116,
            "offsetY": -197,
            "originX": 110,
            "originY": 222,
            "centerX": -9,
            "centerY": 134,
            "beamSpacing": -2
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/1/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": -1,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "beamSpacing": -2
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/1/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 56,
            "centerY": 172,
            "centerX": 298,
            "fullScreen": false,
            "beamSpacing": -2
        }
    },
    "CHAVE_BEAM_026": {
        "start": {
            "imageUrl": "/Assets/especiais/beans/1/1.gif",
            "frames": 2,
            "frameWidth": 81,
            "frameHeight": 99,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -161,
            "offsetY": -197,
            "originX": 110,
            "originY": 222,
            "centerX": -9,
            "centerY": 134,
            "rotation": -35,
            "beamSpacing": -2
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/1/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 12,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "rotation": -35,
            "beamSpacing": -2
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/1/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 56,
            "centerY": 172,
            "centerX": 298,
            "fullScreen": false,
            "beamSpacing": -2
        }
    },

    "BEAM": {
        "name": "Beam 1",
        "color": "#ffffff",
        "start": {
            "imageUrl": "/Assets/especiais/beans/1/1.gif",
            "frames": 2,
            "frameWidth": 81,
            "frameHeight": 99,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 31,
            "offsetY": -215,
            "originX": 110,
            "originY": 222,
            "centerX": -9,
            "centerY": 134,
            "rotation": -35
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/1/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": -99,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116,
            "projectileOffsetX": -244,
            "projectileWidth": 305,
            "projectileOffsetY": -124,
            "projectileHeight": -249,
            "rotation": -35
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/1/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": -73,
            "centerY": 172,
            "centerX": 298,
            "fullScreen": false
        },
        "beamHueRotate": 0,
        "beamSaturate": 1.2,
        "beamContrast": 3,
        "beamBrightness": 0.85,
        "beamOpacity": 1
    },
    "CHAVE_BEAM_233": {
        "start": {
            "offsetX": -119,
            "offsetY": -187,
            "centerX": -8,
            "centerY": 120
        },
        "middle": {
            "offsetX": 0,
            "offsetY": 23,
            "projectileOffsetX": -244,
            "projectileOffsetY": -124,
            "projectileWidth": 305,
            "projectileHeight": -249,
            "kiOriginX": 61,
            "centerX": -2,
            "centerY": 116
        },
        "end": {
            "offsetX": 0,
            "offsetY": 49,
            "centerX": 298,
            "centerY": 172
        }
    },
    "CHAVE_BEAM_040": {
        "start": {
            "imageUrl": "/Assets/especiais/beans/3/1.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": -334,
            "offsetY": -207,
            "kiOriginX": 47,
            "kiOriginY": 10,
            "beamSpacing": -30,
            "centerY": 24,
            "centerX": 0
        },
        "middle": {
            "imageUrl": "/Assets/especiais/beans/3/2.gif",
            "frames": 1,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": -1,
            "kiOriginX": 47,
            "kiOriginY": 10,
            "centerX": 330,
            "centerY": 367,
            "projectileOffsetX": -244,
            "projectileOffsetY": -124,
            "projectileWidth": 305,
            "projectileHeight": -249
        },
        "end": {
            "imageUrl": "/Assets/especiais/beans/3/3.gif",
            "frames": 2,
            "frameWidth": 0,
            "frameHeight": 0,
            "isGif": true,
            "speed": 4,
            "loop": true,
            "offsetX": 0,
            "offsetY": 35,
            "centerY": 219,
            "beamSpacing": -30,
            "centerX": 0
        }
    }
};
