import { CharacterData, PlayerState } from '../types';

const COMMIT = '062ee044e3dc31740de010588c7bed60a9750da4';
const BASE_URL = `/Assets/personagens/freeza/`;

const getUrl = (subPath: string) => `${BASE_URL}${subPath}`;

const URLS = {
  agachado: "/Assets/personagens/freeza/agachado.gif",
  aterrisando: "/Assets/personagens/freeza/aterrisando.gif",
  caindo: "/Assets/personagens/freeza/caindo.gif",
  carregando_ki_1: "/Assets/personagens/freeza/carregamdo_ki_1.gif",
  carregando_ki_2: "/Assets/personagens/freeza/carregamdo_ki_2.gif",
  carregando_ki_3: "/Assets/personagens/freeza/carregamdo_ki_3.gif",
  dano_1: "/Assets/personagens/freeza/dano_1.gif",
  defesa: "/Assets/personagens/freeza/defesa.gif",
  defesa_agachado: "/Assets/personagens/freeza/defesa_agachado.gif",
  defesa_ar: "/Assets/personagens/freeza/defesa_ar.gif",
  double_tap: "/Assets/personagens/freeza/double_tap.gif",
  dragon_rush_1: "/Assets/personagens/freeza/dragon_rush_1.gif",
  dragon_rush_2: "/Assets/personagens/freeza/dragon_rush_2.gif",
  dragon_rush_3: "/Assets/personagens/freeza/dragon_rush_3.gif",
  entrada_por_ko: "/Assets/personagens/freeza/entrada_por_ko.gif",
  especial_1_1: "/Assets/personagens/freeza/especial_1_1.gif",
  especial_1_2: "/Assets/personagens/freeza/especial_1_2.gif",
  especial_2_1: "/Assets/personagens/freeza/especial_2_1.gif",
  especial_2_2: "/Assets/personagens/freeza/especial_2_2.gif",
  especial_3_1: "/Assets/personagens/freeza/especial_3_1.gif",
  especial_3_2: "/Assets/personagens/freeza/especial_3_2.gif",
  especial_4_1: "/Assets/personagens/freeza/especial_4_1.gif",
  especial_4_2: "/Assets/personagens/freeza/especial_4_2.gif",
  especial_4_3: "/Assets/personagens/freeza/especial_4_3.gif",
  especial_kiblast_1: "/Assets/personagens/freeza/especial_kiblast_1.gif",
  especial_kiblast_2: "/Assets/personagens/freeza/especial_kiblast_2.gif",
  especial_kiblast_ar_1: "/Assets/personagens/freeza/especial_kiblast_ar_1.gif",
  especial_kiblast_ar_2: "/Assets/personagens/freeza/especial_kiblast_ar_2.gif",
  frente: "/Assets/personagens/freeza/frente.gif",
  introducao_1_1: "/Assets/personagens/freeza/introducao_1_1.gif",
  introducao_1_2: "/Assets/personagens/freeza/introducao_1_2.gif",
  introducao_1_3: "/Assets/personagens/freeza/introducao_1_3.gif",
  introducao_1_4: "/Assets/personagens/freeza/introducao_1_4.gif",
  introducao_1_5: "/Assets/personagens/freeza/introducao_1_5.gif",
  introducao_1_6: "/Assets/personagens/freeza/introducao_1_6.gif",
  introducao_1_7: "/Assets/personagens/freeza/introducao_1_7.gif",
  introducao_1_8: "/Assets/personagens/freeza/introducao_1_8.gif",
  introducao_1_9: "/Assets/personagens/freeza/introducao_1_9.gif",
  parado: "/Assets/personagens/freeza/parado.gif",
  pulo: "/Assets/personagens/freeza/pulo.gif",
  sparking: "/Assets/personagens/freeza/carregamdo_ki_2.gif",
  super_dash_1: "/Assets/personagens/freeza/super_dash_1.gif",
  super_dash_2: "/Assets/personagens/freeza/super_dash_2.gif",
  tras: "/Assets/personagens/freeza/tras.gif",
  ultimate_1_1: "/Assets/personagens/freeza/ultimate_1_1.gif",
  ultimate_1_2: "/Assets/personagens/freeza/ultimate_1_2.gif",
  ultimate_1_3: "/Assets/personagens/freeza/ultimate_1_3.gif",
  ultimate_2_1: "/Assets/personagens/freeza/ultimate_2_1.gif",
  ultimate_2_2: "/Assets/personagens/freeza/ultimate_2_2.gif",
  ultimate_2_3: "/Assets/personagens/freeza/ultimate_2_3.gif",
  ultimate_2_4: "/Assets/personagens/freeza/ultimate_2_4.gif",
};

const DEFAULT_RPG = { level: 20, currentXp: 0, xpToNextLevel: 100, availablePoints: 50 };

const createGifAnim = (
  url: string,
  loop: boolean = true,
  speed: number = 5,
  customScale?: number
) => ({
  imageUrl: url,
  frames: 1,
  frameWidth: 0,
  frameHeight: 0,
  isGif: true,
  speed,
  loop,
  scale: customScale || 2.2,
});

export const FriezaFinal: CharacterData = {
  id: "frieza_final",
  name: "FREEZA",
  color: "#a855f7",
  rarity: "EPIC",
  tags: ["VILLAIN", "FRIEZA_FORCE"],
  introText: "Oh ho ho ho! É hora de eliminar todos esses vermes insolentes!",
  stats: {
    attack: 12,
    defense: 10,
    speed: 11,
  },
  ...DEFAULT_RPG,
  spriteConfig: {
    defaultScale: 2.2,
    portraitUrl: "/Assets/personagens/freeza/preview.png",
    hitboxWidth: 49,
    hitboxHeight: 101,
    hitboxOffsetX: 30,
    hitboxOffsetY: 75,
    animations: {
      [PlayerState.INTRO]: createGifAnim(URLS.introducao_1_1, false),
      INTRO_1: createGifAnim(URLS.introducao_1_1, false),
      INTRO_2: createGifAnim(URLS.introducao_1_2, false),
      INTRO_3: createGifAnim(URLS.introducao_1_3, false),
      INTRO_4: createGifAnim(URLS.introducao_1_4, false),
      INTRO_5: createGifAnim(URLS.introducao_1_5, false),
      INTRO_6: createGifAnim(URLS.introducao_1_6, false),
      INTRO_7: createGifAnim(URLS.introducao_1_7, false),
      INTRO_8: createGifAnim(URLS.introducao_1_8, false),
      INTRO_9: createGifAnim(URLS.introducao_1_9, false),

      [PlayerState.IDLE]: createGifAnim(URLS.parado, true),
      [PlayerState.RUNNING]: createGifAnim(URLS.frente, true),
      [PlayerState.WALK_BACKWARD]: createGifAnim(URLS.tras, true),
      [PlayerState.DASH_START]: createGifAnim(URLS.super_dash_1, false),
      [PlayerState.DASHING]: createGifAnim(URLS.super_dash_2, true),
      [PlayerState.DASH_END]: createGifAnim(URLS.super_dash_2, false),
      [PlayerState.CROUCH]: createGifAnim(URLS.agachado, true),
      [PlayerState.JUMPING]: createGifAnim(URLS.pulo, false),
      [PlayerState.FALLING]: createGifAnim(URLS.pulo, true),
      FALLING_LOOP: createGifAnim(URLS.pulo, true),
      [PlayerState.LANDING]: createGifAnim(URLS.aterrisando, false),
      GROUND_HIT: createGifAnim(URLS.dano_1, false),
      GROUND_BOUNCE: createGifAnim(URLS.dano_1, false),
      FALL: createGifAnim(URLS.pulo, true),
      [PlayerState.FALLING_HIT]: createGifAnim(URLS.dano_1, true),
      [PlayerState.FALLING_HIT_GROUND]: createGifAnim(URLS.dano_1, false),

      [PlayerState.CHARGE_START]: createGifAnim(URLS.carregando_ki_1, false),
      [PlayerState.CHARGING]: createGifAnim(URLS.carregando_ki_2, true),
      [PlayerState.CHARGE_END]: createGifAnim(URLS.carregando_ki_3, false),

      [PlayerState.BLOCKING]: createGifAnim(URLS.defesa, false),
      [PlayerState.BLOCKING_CROUCH]: createGifAnim(URLS.defesa_agachado, false),
      [PlayerState.BLOCKING_AIR]: createGifAnim(URLS.defesa_ar, false),

      [PlayerState.HIT]: createGifAnim(URLS.dano_1, false),
      [PlayerState.HIT_2]: createGifAnim(URLS.dano_1, false),
      [PlayerState.HIT_3]: createGifAnim(URLS.dano_1, false),
      [PlayerState.STUNNED]: createGifAnim(URLS.dano_1, false),
      [PlayerState.GUARD_BREAK]: createGifAnim(URLS.dano_1, false),
      [PlayerState.KNOCKED_DOWN]: createGifAnim(URLS.dano_1, false),
      [PlayerState.DEFEAT]: createGifAnim(URLS.dano_1, false),

      [PlayerState.VANISH]: createGifAnim(URLS.double_tap, false),
      [PlayerState.VANISH_APPEAR]: createGifAnim(URLS.double_tap, false),
      TELEPORT: createGifAnim(URLS.double_tap, false),
      TELEPORTE: createGifAnim(URLS.double_tap, false),
      [PlayerState.SPARKING]: createGifAnim(URLS.sparking, true),

      [PlayerState.SUPER_DASH]: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_1: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_2: createGifAnim(URLS.super_dash_2, true, 5),
      super_dash_2: createGifAnim(URLS.super_dash_2, true, 5),
      [PlayerState.QUICK_DASH]: createGifAnim(URLS.double_tap, false),
      DOUBLE_TAP: createGifAnim(URLS.double_tap, false),
      [PlayerState.DRAGON_RUSH]: createGifAnim(URLS.dragon_rush_1, false),
      [PlayerState.DRAGON_COMBO]: createGifAnim(URLS.dragon_rush_2, false),
      [PlayerState.DRAGON_DASH_FOLLOW]: createGifAnim(URLS.dragon_rush_3, false),
      dragon_rush_2: createGifAnim(URLS.dragon_rush_2, false),
      dragon_rush_3: createGifAnim(URLS.dragon_rush_3, false),

      KI_BLAST_1: createGifAnim(URLS.especial_kiblast_1, false),
      KI_BLAST_2: createGifAnim(URLS.especial_kiblast_2, false),
      KI_BLAST_AR_1: createGifAnim(URLS.especial_kiblast_ar_1, false),
      KI_BLAST_AR_2: createGifAnim(URLS.especial_kiblast_ar_2, false),

      Especial_1_1: createGifAnim(URLS.especial_1_1, false),
      Especial_1_2: createGifAnim(URLS.especial_1_2, false),

      Especial_2_1: createGifAnim(URLS.especial_2_1, false),
      Especial_2_2: createGifAnim(URLS.especial_2_2, false),

      Especial_3_1: createGifAnim(URLS.especial_3_1, false),
      Especial_3_2: createGifAnim(URLS.especial_3_2, false),

      Especial_4_1: createGifAnim(URLS.especial_4_1, false),
      Especial_4_2: createGifAnim(URLS.especial_4_2, false),
      Especial_4_3: createGifAnim(URLS.especial_4_3, false),

      Ultimate_1_1: createGifAnim(URLS.ultimate_1_1, false),
      Ultimate_1_2: createGifAnim(URLS.ultimate_1_2, false),
      Ultimate_1_3: createGifAnim(URLS.ultimate_1_3, false),

      Ultimate_2_1: createGifAnim(URLS.ultimate_2_1, false),
      Ultimate_2_2: createGifAnim(URLS.ultimate_2_2, false),
      Ultimate_2_3: createGifAnim(URLS.ultimate_2_3, false),
      Ultimate_2_4: createGifAnim(URLS.ultimate_2_4, false),

      [PlayerState.STANDBY]: createGifAnim(URLS.parado, true),
      TAG_IN_KO: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_IN]: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_OUT]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_ENTRY]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_EXIT]: createGifAnim(URLS.parado, false),
      [PlayerState.VICTORY]: createGifAnim(URLS.parado, false),
    }
  }
};
