import { CharacterData, PlayerState } from '../types';
import { GokuBlue_Beams } from './beams/GokuBlue_Beams';

const BASE_URL = "/Assets/personagens/gokublue/";

const URLS = {
  agachado: `${BASE_URL}agachado.gif`,
  aterrissando: `${BASE_URL}aterrissando.gif`,
  caindo: `${BASE_URL}caindo.gif`,
  carregando_ki_1: `${BASE_URL}carregando_ki_1.gif`,
  carregando_ki_2: `${BASE_URL}carregando_ki_2.gif`,
  carregando_ki_3: `${BASE_URL}carregando_ki_3.gif`,
  defesa: `${BASE_URL}defesa.gif`,
  defesa_agachado: `${BASE_URL}defesa_agachado.gif`,
  defesa_ar: `${BASE_URL}defesa_ar.gif`,
  double_tap: `${BASE_URL}double_tap.gif`,
  dragon_rush_1: `${BASE_URL}dragon_rush_1.gif`,
  dragon_rush_2: `${BASE_URL}dragon_rush_2.gif`,
  dragon_rush_3: `${BASE_URL}dragon_rush_3.gif`,
  entrada_por_ko: `${BASE_URL}entrada_por_ko.gif`,
  especial_2_1: `${BASE_URL}especial_2_1.gif`,
  especial_2_2: `${BASE_URL}especial_2_2.gif`,
  especial_2_3: `${BASE_URL}especial_2_3.gif`,
  especial_2_4: `${BASE_URL}especial_2_4.gif`,
  especial_3_1: `${BASE_URL}especial_3_1.gif`,
  especial_3_2: `${BASE_URL}especial_3_2.gif`,
  especial_3_3: `${BASE_URL}especial_3_3.gif`,
  especial_3_4: `${BASE_URL}especial_3_4.gif`,
  especial_3_5: `${BASE_URL}especial_3_5.gif`,
  especial_kiblast_1: `${BASE_URL}especial_kiblast_1.gif`,
  especial_kiblast_2: `${BASE_URL}especial_kiblast_2.gif`,
  especial_kiblast_ar_1: `${BASE_URL}especial_kiblast_ar_1.gif`,
  especial_kiblast_ar_2: `${BASE_URL}especial_kiblast_ar_2.gif`,
  frente: `${BASE_URL}frente.gif`,
  introducao_1_1: `${BASE_URL}introducao_1_1.gif`,
  introducao_1_2: `${BASE_URL}introducao_1_2.gif`,
  introducao_1_3: `${BASE_URL}introducao_1_3.gif`,
  introducao_1_4: `${BASE_URL}introducao_1_4.gif`,
  introducao_1_5: `${BASE_URL}introducao_1_5.gif`,
  parado: `${BASE_URL}parado.gif`,
  pulo: `${BASE_URL}pulo.gif`,
  sparking: `${BASE_URL}sparking.gif`,
  teleporte: `${BASE_URL}teleporte.gif`,
  transformacao_mui_1: `${BASE_URL}transformacao_mui_1.gif`,
  transformacao_mui_2: `${BASE_URL}transformacao_mui_2.gif`,
  transformacao_mui_3: `${BASE_URL}transformacao_mui_3.gif`,
  transformacao_mui_4: `${BASE_URL}transformacao_mui_4.gif`,
  transformacao_mui_5: `${BASE_URL}transformacao_mui_5.gif`,
  tras: `${BASE_URL}tras.gif`,
  ultimate_1_1: `${BASE_URL}ultimate_1_1.gif`,
  ultimate_1_2: `${BASE_URL}ultimate_1_2.gif`,
  ultimate_1_3: `${BASE_URL}ultimate_1_3.gif`,
  ultimate_1_4: `${BASE_URL}ultimate_1_4.gif`,
  ultimate_1_5: `${BASE_URL}ultimate_1_5.gif`,
  ultimate_2_1: `${BASE_URL}ultimate_2_1.gif`,
  ultimate_2_2: `${BASE_URL}ultimate_2_2.gif`,
  ultimate_2_3: `${BASE_URL}ultimate_2_3.gif`,
  ultimate_2_4: `${BASE_URL}ultimate_2_4.gif`,
  ultimate_2_5: `${BASE_URL}ultimate_2_5.gif`,
};

const createGifAnim = (url: string, loop: boolean = true, speed: number = 5) => ({
  imageUrl: url,
  frames: 1,
  frameWidth: 0,
  frameHeight: 0,
  isGif: true,
  speed,
  loop,
  scale: 2.2,
});

export const GokuBlue: CharacterData = {
  id: "goku_blue",
  name: "GOKU BLUE",
  color: "#3b82f6",
  rarity: "EPIC",
  tags: ["SAIYAN", "HERO", "GOD", "BLUE"],
  transformTo: ["goku_mui"],
  detransformTo: ["goku_ssj", "goku_base"],
  beamOverrides: GokuBlue_Beams,
  introText: "Este é o poder do Super Saiyajin Blue!",
  stats: {
    attack: 15,
    defense: 12,
    speed: 15,
  },
  level: 1,
  currentXp: 0,
  xpToNextLevel: 100,
  availablePoints: 0,
  spriteConfig: {
    defaultScale: 2.2,
    portraitUrl: `${BASE_URL}prewiew.gif`,
    hitboxWidth: 49,
    hitboxHeight: 101,
    hitboxOffsetX: 26,
    hitboxOffsetY: 79,
    animations: {
      [PlayerState.INTRO]: createGifAnim(URLS.introducao_1_1, false),
      INTRO_1: createGifAnim(URLS.introducao_1_1, false),
      INTRO_2: createGifAnim(URLS.introducao_1_2, false),
      INTRO_3: createGifAnim(URLS.introducao_1_3, false),
      INTRO_4: createGifAnim(URLS.introducao_1_4, false),
      INTRO_5: createGifAnim(URLS.introducao_1_5, false),

      [PlayerState.IDLE]: createGifAnim(URLS.parado, true),
      [PlayerState.RUNNING]: createGifAnim(URLS.frente, true),
      [PlayerState.WALK_BACKWARD]: createGifAnim(URLS.tras, true),
      [PlayerState.DASH_START]: createGifAnim("/Assets/personagens/gokubase/super_dash_1.gif", false),
      [PlayerState.DASHING]: createGifAnim("/Assets/personagens/gokubase/super_dash_2.gif", true),
      [PlayerState.DASH_END]: createGifAnim("/Assets/personagens/gokubase/super_dash_2.gif", false),
      [PlayerState.CROUCH]: createGifAnim(URLS.agachado, true),
      [PlayerState.JUMPING]: createGifAnim(URLS.pulo, false),
      [PlayerState.FALLING]: createGifAnim(URLS.pulo, true),
      FALLING_LOOP: createGifAnim(URLS.pulo, true),
      [PlayerState.LANDING]: createGifAnim(URLS.aterrissando, false),
      LANDING_FALL: createGifAnim(URLS.aterrissando, false),
      GROUND_HIT: createGifAnim(URLS.aterrissando, false),
      GROUND_BOUNCE: createGifAnim(URLS.aterrissando, false),
      FALL: createGifAnim(URLS.pulo, true),
      [PlayerState.FALLING_HIT]: createGifAnim("/Assets/personagens/gokubase/hit_air_fall.gif", true),
      [PlayerState.FALLING_HIT_GROUND]: createGifAnim(URLS.aterrissando, false),

      [PlayerState.CHARGE_START]: createGifAnim(URLS.carregando_ki_1, false),
      [PlayerState.CHARGING]: {
        imageUrl: URLS.carregando_ki_2,
        frames: 3,
        frameWidth: 31,
        frameHeight: 47,
        isGif: true,
        speed: 5,
        loop: true,
        scale: 2.2,
        offsetX: 0,
        offsetY: 0,
        auraConfigKey: "CHAVE_AURA_008"
      },
      [PlayerState.CHARGE_END]: createGifAnim(URLS.carregando_ki_3, false),

      [PlayerState.BLOCKING]: createGifAnim(URLS.defesa, false),
      [PlayerState.BLOCKING_CROUCH]: createGifAnim(URLS.defesa_agachado, false),
      [PlayerState.BLOCKING_AIR]: createGifAnim(URLS.defesa_ar, false),

      [PlayerState.HIT]: createGifAnim("/Assets/personagens/gokubase/hit_light.gif", false),
      [PlayerState.HIT_2]: createGifAnim("/Assets/personagens/gokubase/hit_medium.gif", false),
      [PlayerState.HIT_3]: createGifAnim("/Assets/personagens/gokubase/hit_heavy.gif", false),
      HIT_HIGH_LIGHT: createGifAnim("/Assets/personagens/gokubase/hit_light.gif", false),
      HIT_HIGH_MEDIUM: createGifAnim("/Assets/personagens/gokubase/hit_medium.gif", false),
      HIT_HIGH_HARD: createGifAnim("/Assets/personagens/gokubase/hit_heavy.gif", false),
      HIT_LOW_LIGHT: createGifAnim("/Assets/personagens/gokubase/hit_light.gif", false),
      HIT_LOW_HARD: createGifAnim("/Assets/personagens/gokubase/hit_medium.gif", false),
      CROUCH_HIT: createGifAnim("/Assets/personagens/gokubase/hit_light.gif", false),
      AIR_HIT: createGifAnim("/Assets/personagens/gokubase/hit_air.gif", false),
      LAUNCHED: createGifAnim("/Assets/personagens/gokubase/hit_launch.gif", false),
      GROUND_LAUNCH: createGifAnim("/Assets/personagens/gokubase/hit_ground_launch.gif", false),
      [PlayerState.STUNNED]: createGifAnim("/Assets/personagens/gokubase/hit_ground_stun.gif", false),
      [PlayerState.GUARD_BREAK]: createGifAnim("/Assets/personagens/gokubase/hit_heavy.gif", false),
      [PlayerState.KNOCKED_DOWN]: createGifAnim("/Assets/personagens/gokubase/hit_ground_stun.gif", false),
      [PlayerState.DEFEAT]: createGifAnim("/Assets/personagens/gokubase/hit_ground_crash.gif", false),

      [PlayerState.VANISH]: createGifAnim(URLS.teleporte, false),
      [PlayerState.VANISH_APPEAR]: createGifAnim(URLS.teleporte, false),
      TELEPORT: createGifAnim(URLS.teleporte, false),
      TELEPORTE: createGifAnim(URLS.teleporte, false),

      [PlayerState.SPARKING]: createGifAnim(URLS.sparking, true),
      [PlayerState.SUPER_DASH]: createGifAnim(URLS.dragon_rush_1, true, 5),
      SUPER_DASH_1: createGifAnim("/Assets/personagens/gokubase/super_dash_1.gif", true, 5),
      SUPER_DASH_2: createGifAnim("/Assets/personagens/gokubase/super_dash_2.gif", true, 5),
      super_dash_2: createGifAnim("/Assets/personagens/gokubase/super_dash_2.gif", true, 5),

      [PlayerState.QUICK_DASH]: createGifAnim(URLS.double_tap, false),
      [PlayerState.DRAGON_RUSH]: createGifAnim(URLS.dragon_rush_1, false),
      [PlayerState.DRAGON_COMBO]: createGifAnim(URLS.dragon_rush_2, false),
      [PlayerState.DRAGON_DASH_FOLLOW]: createGifAnim(URLS.dragon_rush_3, false),
      dragon_rush_2: createGifAnim(URLS.dragon_rush_2, false),
      dragon_rush_3: createGifAnim(URLS.dragon_rush_3, false),

      KI_BLAST_1: createGifAnim(URLS.especial_kiblast_1, false),
      KI_BLAST_2: createGifAnim(URLS.especial_kiblast_2, false),
      KI_BLAST_AR_1: createGifAnim(URLS.especial_kiblast_ar_1, false),
      KI_BLAST_AR_2: createGifAnim(URLS.especial_kiblast_ar_2, false),
      
      Especial_2_1: createGifAnim(URLS.especial_2_1, false),
      Especial_2_2: createGifAnim(URLS.especial_2_2, false),
      Especial_2_3: createGifAnim(URLS.especial_2_3, false),
      Especial_2_4: createGifAnim(URLS.especial_2_4, false),
      Especial_3_1: createGifAnim(URLS.especial_3_1, false),
      Especial_3_2: createGifAnim(URLS.especial_3_2, false),
      Especial_3_3: createGifAnim(URLS.especial_3_3, false),
      Especial_3_4: createGifAnim(URLS.especial_3_4, false),
      Especial_3_5: createGifAnim(URLS.especial_3_5, false),

      Ultimate_1_1: createGifAnim(URLS.ultimate_1_1, false),
      Ultimate_1_2: createGifAnim(URLS.ultimate_1_2, false),
      Ultimate_1_3: createGifAnim(URLS.ultimate_1_3, false),
      Ultimate_1_4: createGifAnim(URLS.ultimate_1_4, false),
      Ultimate_1_5: {
        ...createGifAnim(URLS.ultimate_1_5, false),
        createsBeam: "CHAVE_BEAM_004"
      },

      Ultimate_2_1: createGifAnim(URLS.ultimate_2_1, false),
      Ultimate_2_2: createGifAnim(URLS.ultimate_2_2, false),
      Ultimate_2_3: createGifAnim(URLS.ultimate_2_3, false),
      Ultimate_2_4: createGifAnim(URLS.ultimate_2_4, false),
      Ultimate_2_5: createGifAnim(URLS.ultimate_2_5, false),

      [PlayerState.TRANSFORM]: createGifAnim(URLS.transformacao_mui_1, false),
      TRANSFORM_GOKU_MUI_1: createGifAnim(URLS.transformacao_mui_1, false),
      TRANSFORM_GOKU_MUI_2: createGifAnim(URLS.transformacao_mui_2, false),
      TRANSFORM_GOKU_MUI_3: createGifAnim(URLS.transformacao_mui_3, false),
      TRANSFORM_GOKU_MUI_4: createGifAnim(URLS.transformacao_mui_4, false),
      TRANSFORM_GOKU_MUI_5: createGifAnim(URLS.transformacao_mui_5, false),
      [PlayerState.STANDBY]: createGifAnim(URLS.parado, true),
      TAG_IN_KO: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_IN]: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_OUT]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_ENTRY]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_EXIT]: createGifAnim(URLS.parado, false),
      [PlayerState.VICTORY]: createGifAnim(URLS.parado, false),
    }
  }
};
