import { CharacterData, PlayerState } from '../types';
import { GokuSSJ_Beams } from './beams/GokuSSJ_Beams';

const BASE_URL = "/Assets/personagens/gokussj/";

const URLS = {
  agachado: `${BASE_URL}agachado.gif`,
  aterrissagem: `${BASE_URL}aterrissagem.gif`,
  caindo: `${BASE_URL}caindo.gif`,
  carregando_ki_1: `${BASE_URL}carregando_ki_1.gif`,
  carregando_ki_2: `${BASE_URL}carregando_ki_2.gif`,
  carregando_ki_3: `${BASE_URL}carregando_ki_3.gif`,
  dano_1: `${BASE_URL}caindo.gif`,
  dano_2: `${BASE_URL}caindo.gif`,
  dano_3: `${BASE_URL}caindo.gif`,
  dano_4: `${BASE_URL}caindo.gif`,
  defesa: `${BASE_URL}defesa.gif`,
  defesa_agachado: `${BASE_URL}defesa_agachado.gif`,
  defesa_ar: `${BASE_URL}defesa_ar.gif`,
  desfazendo_transformacao_base_1: `${BASE_URL}desfazendo_transformacao_base_1.gif`,
  desfazendo_transformacao_base_2: `${BASE_URL}desfazendo_transformacao_base_2.gif`,
  double_tap: `${BASE_URL}double_tap.gif`,
  dragon_rush_1: `${BASE_URL}dragon_rush_1.gif`,
  dragon_rush_2: `${BASE_URL}dragon_rush_2.gif`,
  dragon_rush_3: `${BASE_URL}dragon_rush_3.gif`,
  entrada_por_ko: `${BASE_URL}entrada_por_ko.gif`,
  especial_1_1: `${BASE_URL}especial_1_1.gif`,
  especial_1_2: `${BASE_URL}especial_1_2.gif`,
  especial_2_1: `${BASE_URL}especial_2_1.gif`,
  especial_2_2: `${BASE_URL}especial_2_2.gif`,
  especial_2_3: `${BASE_URL}especial_2_3.gif`,
  especial_2_4: `${BASE_URL}especial_2_4.gif`,
  especial_2_5: `${BASE_URL}especial_2_5.gif`,
  especial_2_6: `${BASE_URL}especial_2_6.gif`,
  especial_2_7: `${BASE_URL}especial_2_7.gif`,
  especial_3_1: `${BASE_URL}especial_1_1.gif`,
  especial_3_2: `${BASE_URL}especial_1_2.gif`,
  especial_3_3: `${BASE_URL}especial_2_1.gif`,
  especial_4_1: `${BASE_URL}especial_2_2.gif`,
  especial_4_2: `${BASE_URL}especial_2_3.gif`,
  especial_kiblast_1: `${BASE_URL}especial_kiblast_1.gif`,
  especial_kiblast_2: `${BASE_URL}especial_kiblast_2.gif`,
  especial_kiblast_ar_1: `${BASE_URL}especial_kiblast_ar_1.gif`,
  especial_kiblast_ar_2: `${BASE_URL}especial_kiblast_ar_2.gif`,
  frente: `${BASE_URL}frente.gif`,
  introducao_1_1: `${BASE_URL}introducao_1_1.gif`,
  introducao_1_2: `${BASE_URL}introducao_1_2.gif`,
  introducao_1_3: `${BASE_URL}introducao_1_3.gif`,
  introducao_1_4: `${BASE_URL}introducao_1_4.gif`,
  introducao_1_5: `${BASE_URL}introducao_1_5.gif`,
  introducao_1_6: `${BASE_URL}introducao_1_6.gif`,
  parado: `${BASE_URL}parado.gif`,
  pulo: `${BASE_URL}pulo.gif`,
  sparking: `${BASE_URL}sparking.gif`,
  super_dash_1: `${BASE_URL}super_dash_1.gif`,
  super_dash_2: `${BASE_URL}super_dash_2.gif`,
  teleporte: `${BASE_URL}teleporte.gif`,
  transformacao_blue_1: `${BASE_URL}transformacao_blue_1.gif`,
  transformacao_blue_2: `${BASE_URL}transformacao_blue_2.gif`,
  transformacao_blue_3: `${BASE_URL}transformacao_blue_3.gif`,
  transformacao_blue_4: `${BASE_URL}transformacao_blue_4.gif`,
  transformacao_blue_5: `${BASE_URL}transformacao_blue_5.gif`,
  transformacao_mui_1: `${BASE_URL}transformacao_mui_1.gif`,
  transformacao_mui_2: `${BASE_URL}transformacao_mui_2.gif`,
  transformacao_mui_3: `${BASE_URL}transformacao_mui_3.gif`,
  transformacao_mui_4: `${BASE_URL}transformacao_mui_4.gif`,
  transformacao_mui_5: `${BASE_URL}transformacao_mui_5.gif`,
  transformacao_mui_6: `${BASE_URL}transformacao_mui_6.gif`,
  tras: `${BASE_URL}tras.gif`,
  ultimate_1_1: `${BASE_URL}ultimate_1_1.gif`,
  ultimate_1_2: `${BASE_URL}ultimate_1_2.gif`,
  ultimate_1_3: `${BASE_URL}ultimate_1_3.gif`,
  ultimate_1_4: `${BASE_URL}ultimate_1_4.gif`,
  ultimate_2_1: `${BASE_URL}ultimate_2_1.gif`,
  ultimate_2_2: `${BASE_URL}ultimate_2_2.gif`,
  ultimate_2_3: `${BASE_URL}ultimate_2_3.gif`,
  ultimate_2_4: `${BASE_URL}ultimate_2_4.gif`,
  ultimate_2_5: `${BASE_URL}ultimate_2_5.gif`,
  ultimate_2_6: `${BASE_URL}ultimate_2_6.gif`,
};

const createGifAnim = (url: string, loop: boolean = true, speed: number = 5) => ({
  imageUrl: url,
  frames: 1,
  frameWidth: 0,
  frameHeight: 0,
  isGif: true,
  speed,
  loop,
  scale: 2.2,
});

export const GokuSSJ: CharacterData = {
  id: "goku_ssj",
  name: "GOKU SSJ",
  color: "#eab308",
  rarity: "RARE",
  tags: ["SAIYAN", "HERO", "SSJ"],
  transformTo: ["goku_blue", "goku_mui"],
  detransformTo: ["goku_base"],
  beamOverrides: GokuSSJ_Beams,
  introText: "Eu sou o Super Saiyajin, Son Goku!",
  stats: {
    attack: 12,
    defense: 10,
    speed: 12,
  },
  level: 1,
  currentXp: 0,
  xpToNextLevel: 100,
  availablePoints: 0,
  spriteConfig: {
    defaultScale: 2.2,
    portraitUrl: `${BASE_URL}prewiew.png`,
    hitboxWidth: 49,
    hitboxHeight: 101,
    hitboxOffsetX: 26,
    hitboxOffsetY: 79,
    animations: {
      [PlayerState.INTRO]: createGifAnim(URLS.introducao_1_1, false),
      INTRO_1: createGifAnim(URLS.introducao_1_1, false),
      INTRO_2: createGifAnim(URLS.introducao_1_2, false),
      INTRO_3: createGifAnim(URLS.introducao_1_3, false),
      INTRO_4: createGifAnim(URLS.introducao_1_4, false),
      INTRO_5: createGifAnim(URLS.introducao_1_5, false),
      INTRO_6: createGifAnim(URLS.introducao_1_6, false),

      [PlayerState.IDLE]: createGifAnim(URLS.parado, true),
      [PlayerState.RUNNING]: createGifAnim(URLS.frente, true),
      [PlayerState.WALK_BACKWARD]: createGifAnim(URLS.tras, true),
      [PlayerState.DASH_START]: createGifAnim(URLS.super_dash_1, false),
      [PlayerState.DASHING]: createGifAnim(URLS.super_dash_2, true),
      [PlayerState.DASH_END]: createGifAnim(URLS.super_dash_2, false),
      [PlayerState.CROUCH]: createGifAnim(URLS.agachado, true),
      [PlayerState.JUMPING]: createGifAnim(URLS.pulo, false),
      [PlayerState.FALLING]: createGifAnim(URLS.pulo, true),
      FALLING_LOOP: createGifAnim(URLS.pulo, true),
      [PlayerState.LANDING]: createGifAnim(URLS.aterrissagem, false),
      GROUND_HIT: createGifAnim(URLS.dano_1, false),
      GROUND_BOUNCE: createGifAnim(URLS.dano_1, false),
      FALL: createGifAnim(URLS.pulo, true),
      [PlayerState.FALLING_HIT]: createGifAnim(URLS.dano_1, true),
      [PlayerState.FALLING_HIT_GROUND]: createGifAnim(URLS.dano_1, false),

      [PlayerState.CHARGE_START]: createGifAnim(URLS.carregando_ki_1, false),
      [PlayerState.CHARGING]: {
        ...createGifAnim(URLS.carregando_ki_2, true),
        auraConfigKey: "CHAVE_AURA_003"
      },
      [PlayerState.CHARGE_END]: createGifAnim(URLS.carregando_ki_3, false),

      [PlayerState.BLOCKING]: createGifAnim(URLS.defesa, false),
      [PlayerState.BLOCKING_CROUCH]: createGifAnim(URLS.defesa_agachado, false),
      [PlayerState.BLOCKING_AIR]: createGifAnim(URLS.defesa_ar, false),

      [PlayerState.HIT]: createGifAnim(URLS.dano_1, false),
      [PlayerState.HIT_2]: createGifAnim(URLS.dano_2, false),
      [PlayerState.HIT_3]: createGifAnim(URLS.dano_3, false),
      HIT_HIGH_LIGHT: createGifAnim(URLS.dano_1, false),
      HIT_HIGH_MEDIUM: createGifAnim(URLS.dano_2, false),
      HIT_HIGH_HARD: createGifAnim(URLS.dano_3, false),
      HIT_LOW_LIGHT: createGifAnim(URLS.dano_1, false),
      HIT_LOW_HARD: createGifAnim(URLS.dano_2, false),
      CROUCH_HIT: createGifAnim(URLS.dano_1, false),
      AIR_HIT: createGifAnim(URLS.dano_1, false),
      LAUNCHED: createGifAnim(URLS.dano_1, false),
      GROUND_LAUNCH: createGifAnim(URLS.dano_1, false),
      [PlayerState.STUNNED]: createGifAnim(URLS.dano_1, false),
      [PlayerState.GUARD_BREAK]: createGifAnim(URLS.dano_1, false),
      [PlayerState.KNOCKED_DOWN]: createGifAnim(URLS.dano_1, false),
      [PlayerState.DEFEAT]: createGifAnim(URLS.dano_1, false),

      [PlayerState.VANISH]: createGifAnim(URLS.teleporte, false),
      [PlayerState.VANISH_APPEAR]: createGifAnim(URLS.teleporte, false),
      TELEPORT: createGifAnim(URLS.teleporte, false),
      TELEPORTE: createGifAnim(URLS.teleporte, false),

      [PlayerState.SPARKING]: createGifAnim(URLS.sparking, true),

      [PlayerState.SUPER_DASH]: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_1: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_2: createGifAnim(URLS.super_dash_2, true, 5),
      super_dash_2: createGifAnim(URLS.super_dash_2, true, 5),

      [PlayerState.QUICK_DASH]: createGifAnim(URLS.double_tap, false),
      [PlayerState.DRAGON_RUSH]: createGifAnim(URLS.dragon_rush_1, false),
      [PlayerState.DRAGON_COMBO]: createGifAnim(URLS.dragon_rush_2, false),
      [PlayerState.DRAGON_DASH_FOLLOW]: createGifAnim(URLS.dragon_rush_3, false),
      dragon_rush_2: createGifAnim(URLS.dragon_rush_2, false),
      dragon_rush_3: createGifAnim(URLS.dragon_rush_3, false),

      KI_BLAST_1: createGifAnim(URLS.especial_kiblast_1, false),
      KI_BLAST_2: createGifAnim(URLS.especial_kiblast_2, false),
      KI_BLAST_AR_1: createGifAnim(URLS.especial_kiblast_ar_1, false),
      KI_BLAST_AR_2: createGifAnim(URLS.especial_kiblast_ar_2, false),

      Especial_1_1: createGifAnim(URLS.especial_1_1, false),
      Especial_1_2: {
        ...createGifAnim(URLS.especial_1_2, false),
        createsBeam: "CHAVE_BEAM_45",
        effectConfigKey: "CHAVE_EFFECT_TELACHEIA_05_AZUL"
      },
      Especial_2_1: createGifAnim(URLS.especial_2_1, false),
      Especial_2_2: createGifAnim(URLS.especial_2_2, false),
      Especial_2_3: createGifAnim(URLS.especial_2_3, false),
      Especial_2_4: createGifAnim(URLS.especial_2_4, false),
      Especial_2_5: createGifAnim(URLS.especial_2_5, false),
      Especial_2_6: createGifAnim(URLS.especial_2_6, false),
      Especial_2_7: createGifAnim(URLS.especial_2_7, false),

      Ultimate_1_1: createGifAnim(URLS.ultimate_1_1, false),
      Ultimate_1_2: createGifAnim(URLS.ultimate_1_2, false),
      Ultimate_1_3: createGifAnim(URLS.ultimate_1_3, false),
      Ultimate_1_4: {
        ...createGifAnim(URLS.ultimate_1_4, false),
        createsBeam: "CHAVE_BEAM_48"
      },

      Ultimate_2_1: createGifAnim(URLS.ultimate_2_1, false),
      Ultimate_2_2: createGifAnim(URLS.ultimate_2_2, false),
      Ultimate_2_3: createGifAnim(URLS.ultimate_2_3, false),
      Ultimate_2_4: createGifAnim(URLS.ultimate_2_4, false),
      Ultimate_2_5: createGifAnim(URLS.ultimate_2_5, false),
      Ultimate_2_6: {
        ...createGifAnim(URLS.ultimate_2_6, false),
        createsBeam: "CHAVE_BEAM_47"
      },

      [PlayerState.TRANSFORM]: createGifAnim(URLS.transformacao_blue_1, false),
      TRANSFORM_GOKU_BLUE_1: createGifAnim(URLS.transformacao_blue_1, false),
      TRANSFORM_GOKU_BLUE_2: createGifAnim(URLS.transformacao_blue_2, false),
      TRANSFORM_GOKU_BLUE_3: createGifAnim(URLS.transformacao_blue_3, false),
      TRANSFORM_GOKU_BLUE_4: createGifAnim(URLS.transformacao_blue_4, false),
      TRANSFORM_GOKU_BLUE_5: createGifAnim(URLS.transformacao_blue_5, false),
      TRANSFORM_GOKU_MUI_1: createGifAnim(URLS.transformacao_mui_1, false),
      TRANSFORM_GOKU_MUI_2: createGifAnim(URLS.transformacao_mui_2, false),
      TRANSFORM_GOKU_MUI_3: createGifAnim(URLS.transformacao_mui_3, false),
      TRANSFORM_GOKU_MUI_4: createGifAnim(URLS.transformacao_mui_4, false),
      TRANSFORM_GOKU_MUI_5: createGifAnim(URLS.transformacao_mui_5, false),
      TRANSFORM_GOKU_MUI_6: createGifAnim(URLS.transformacao_mui_6, false),
      DETRANSFORM_1: createGifAnim(URLS.desfazendo_transformacao_base_1, false),
      DETRANSFORM_2: createGifAnim(URLS.desfazendo_transformacao_base_2, false),

      [PlayerState.STANDBY]: createGifAnim(URLS.parado, true),
      TAG_IN_KO: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_IN]: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_OUT]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_ENTRY]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_EXIT]: createGifAnim(URLS.parado, false),

      [PlayerState.VICTORY]: createGifAnim(URLS.parado, false),
    }
  }
};
