import { CharacterData, PlayerState } from "../types";

const URLS = {
  agachado: "/Assets/personagens/gokumui/agachado.gif",
  aterrisando: "/Assets/personagens/gokumui/aterrisando.gif",
  caindo: "/Assets/personagens/gokumui/caindo.gif",
  carregando_ki_1: "/Assets/personagens/gokumui/carregando_ki_1.gif",
  carregando_ki_2: "/Assets/personagens/gokumui/carregando_ki_2.gif",
  carregando_ki_3: "/Assets/personagens/gokumui/carregando_ki_3.gif",

  hit_light_1: "/Assets/personagens/gokumui/hit_light_1_face_hit.png",
  hit_light_2: "/Assets/personagens/gokumui/hit_light_2_body_hit.png",
  hit_light_3: "/Assets/personagens/gokumui/hit_light_3_recoil.png",
  hit_medium_1: "/Assets/personagens/gokumui/hit_medium_1_stagger.png",
  hit_medium_2: "/Assets/personagens/gokumui/hit_medium_2_body_recoil.png",
  hit_medium_3: "/Assets/personagens/gokumui/hit_medium_3_knockback.png",
  hit_heavy_start: "/Assets/personagens/gokumui/hit_heavy_blowback_start.png",
  hit_heavy_air: "/Assets/personagens/gokumui/hit_heavy_blowback_air.png",

  defesa: "/Assets/personagens/gokumui/defesa.gif",
  defesa_agachado: "/Assets/personagens/gokumui/defesa_agachado.gif",
  defesa_ar: "/Assets/personagens/gokumui/defesa_ar.gif",
  desfazendo_transformacao: "/Assets/personagens/gokumui/desfazendo_transformacao_base.gif",
  double_tap: "/Assets/personagens/gokumui/double_tap.gif",
  dragon_rush_1: "/Assets/personagens/gokumui/dragon_rush_1.gif",
  dragon_rush_2: "/Assets/personagens/gokumui/dragon_rush_2.gif",
  dragon_rush_3: "/Assets/personagens/gokumui/dragon_rush_3.gif",
  entrada_por_ko: "/Assets/personagens/gokumui/entrada_por_ko.gif",
  especial_1_1: "/Assets/personagens/gokumui/especial_1_1.gif",
  especial_3_1: "/Assets/personagens/gokumui/especial_3_1.gif",
  especial_3_2: "/Assets/personagens/gokumui/especial_3_2.gif",
  especial_4_1: "/Assets/personagens/gokumui/especial_4_1.gif",
  especial_4_2: "/Assets/personagens/gokumui/especial_4_2.gif",
  especial_5_1: "/Assets/personagens/gokumui/especial_5_1.gif",
  especial_6_1: "/Assets/personagens/gokumui/especial_6_1.gif",
  especial_6_2: "/Assets/personagens/gokumui/especial_6_2.gif",
  especial_6_3: "/Assets/personagens/gokumui/especial_6_3.gif",
  especial_kiblast_1_1: "/Assets/personagens/gokumui/especial_kiblast_1_1.gif",
  especial_kiblast_1_2: "/Assets/personagens/gokumui/especial_kiblast_1_2.gif",
  frente: "/Assets/personagens/gokumui/frente.gif",
  instinto: "/Assets/personagens/gokumui/instinto.gif",
  introducao_1_1: "/Assets/personagens/gokumui/introducao_1_1.gif",
  introducao_1_2: "/Assets/personagens/gokumui/introducao_1_2.gif",
  introducao_1_3: "/Assets/personagens/gokumui/introducao_1_3.gif",
  introducao_1_4: "/Assets/personagens/gokumui/introducao_1_4.gif",
  introducao_1_5: "/Assets/personagens/gokumui/introducao_1_5.gif",
  introducao_1_6: "/Assets/personagens/gokumui/introducao_1_6.gif",
  parado: "/Assets/personagens/gokumui/parado.gif",
  pulo: "/Assets/personagens/gokumui/pulo.gif",
  super_dash_1: "/Assets/personagens/gokumui/super_dash_1.gif",
  super_dash_2: "/Assets/personagens/gokumui/super_dash_2.gif",
  teleporte: "/Assets/personagens/gokumui/teleporte.gif",
  tras: "/Assets/personagens/gokumui/tras.gif",
  ultimate_1_1: "/Assets/personagens/gokumui/ultimate_1_1.gif",
  ultimate_1_2: "/Assets/personagens/gokumui/ultimate_1_2.gif",
  ultimate_1_3: "/Assets/personagens/gokumui/ultimate_1_3.gif",
  ultimate_1_4: "/Assets/personagens/gokumui/ultimate_1_4.gif",
  ultimate_1_5: "/Assets/personagens/gokumui/ultimate_1_5.gif",
  ultimate_1_6: "/Assets/personagens/gokumui/ultimate_1_6.gif",
  ultimate_1_7: "/Assets/personagens/gokumui/ultimate_1_7.gif",
  ultimate_1_8: "/Assets/personagens/gokumui/ultimate_1_8.gif",
  ultimate_1_9: "/Assets/personagens/gokumui/ultimate_1_9.gif",
};

const DEFAULT_RPG = {
  level: 1,
  currentXp: 0,
  xpToNextLevel: 100,
  availablePoints: 0,
};

const createGifAnim = (
  url: string,
  loop: boolean = true,
  speed: number = 5,
) => ({
  imageUrl:
    url ||
    "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
  frames: 1,
  frameWidth: 0,
  frameHeight: 0,
  isGif: true,
  speed,
  loop,
  scale: 2.2,
});

export const GokuMUI: CharacterData = {
  id: "goku_mui",
  name: "GOKU (MUI)",
  color: "#e2e8f0",
  rarity: "LEGENDARY",
  tags: ["SAIYAN", "GOD", "MUI"],
  detransformTo: ["goku_base", "goku_ssj"],
  level: 1,
  currentXp: 0,
  xpToNextLevel: 100,
  availablePoints: 0,
  stats: {
    attack: 16,
    defense: 11,
    speed: 16,
  },

  spriteConfig: {
    defaultScale: 2.2,
    portraitUrl: "/Assets/personagens/gokumui/prewiew.gif",
    iconUrl: "/Assets/personagens/gokumui/prewiew.gif",
    hitboxWidth: 49,
    hitboxHeight: 101,
    hitboxOffsetX: 35,
    hitboxOffsetY: 70,
    animations: {
      [PlayerState.INTRO]: createGifAnim(URLS.introducao_1_1, false),
      INTRO_1: {
        "imageUrl": "/Assets/personagens/gokumui/introducao_1_1.gif",
        "frames": 8,
        "frameWidth": 30,
        "frameHeight": 54,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": 0,
        "offsetY": 0,
        "zoomType": "ZOOM_IN",
        "zoomAmount": 14.2,
        "cameraFocusX": 42,
        "cameraFocusY": 106,
        "cameraRotation": 46
      },
      INTRO_2: {
        "imageUrl": "/Assets/personagens/gokumui/introducao_1_2.gif",
        "frames": 6,
        "frameWidth": 130,
        "frameHeight": 113,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": 0,
        "offsetY": 0,
        "zoomType": "ZOOM_IN",
        "zoomAmount": 3.95,
        "cameraFocusY": 69,
        "cameraFocusX": 53
      },
      INTRO_3: {
        "imageUrl": "/Assets/personagens/gokumui/introducao_1_3.gif",
        "frames": 8,
        "frameWidth": 130,
        "frameHeight": 113,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": 0,
        "offsetY": 0
      },
      INTRO_4: {
        "imageUrl": "/Assets/personagens/gokumui/introducao_1_4.gif",
        "frames": 8,
        "frameWidth": 130,
        "frameHeight": 113,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": 0,
        "offsetY": 0
      },
      INTRO_5: {
        "imageUrl": "/Assets/personagens/gokumui/introducao_1_5.gif",
        "frames": 14,
        "frameWidth": 135,
        "frameHeight": 90,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 0.4,
        "offsetX": 0,
        "offsetY": 10,
        "zoomType": "IMMEDIATE",
        "zoomAmount": 1.5,
        "fullScreen": true
      },
      INTRO_6: {
        "imageUrl": "/Assets/personagens/gokumui/introducao_1_6.gif",
        "frames": 14,
        "frameWidth": 162,
        "frameHeight": 92,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 0.30000000000000016,
        "offsetX": 0,
        "offsetY": 10,
        "fullScreen": true,
        "zoomType": "IMMEDIATE",
        "zoomAmount": 1.5
      },

      [PlayerState.IDLE]: createGifAnim(URLS.parado, true),
      [PlayerState.RUNNING]: createGifAnim(URLS.frente, true),
      [PlayerState.WALK_BACKWARD]: createGifAnim(URLS.tras, true),
      [PlayerState.CROUCH]: createGifAnim(URLS.agachado, true),

      [PlayerState.JUMPING]: createGifAnim(URLS.pulo, false),
      [PlayerState.FALLING]: createGifAnim(URLS.pulo, true),
      FALLING_LOOP: createGifAnim(URLS.pulo, true),
      [PlayerState.LANDING]: createGifAnim(URLS.aterrisando, false),

      KI_BLAST_1: createGifAnim(URLS.especial_kiblast_1_1, false),
      KI_BLAST_2: createGifAnim(URLS.especial_kiblast_1_2, false),
      KI_BLAST_AR_1: createGifAnim(URLS.especial_kiblast_1_1, false),
      KI_BLAST_AR_2: createGifAnim(URLS.especial_kiblast_1_2, false),

      // Specials mapped to what AnimationResolver returns for goku_mui
      SPECIAL_1_1: createGifAnim(URLS.especial_1_1, false),

      SPECIAL_3_1: createGifAnim(URLS.especial_3_1, false),
      SPECIAL_3_2: createGifAnim(URLS.especial_3_2, false),

      SPECIAL_4_1: createGifAnim(URLS.especial_4_1, false),
      SPECIAL_4_2: createGifAnim(URLS.especial_4_2, false),

      SPECIAL_5_1: createGifAnim(URLS.especial_5_1, false),

      SPECIAL_6_1: createGifAnim(URLS.especial_6_1, false),
      SPECIAL_6_2: createGifAnim(URLS.especial_6_2, false),
      SPECIAL_6_3: createGifAnim(URLS.especial_6_3, false),

      [PlayerState.ULTIMATE]: {
        "imageUrl": "/Assets/personagens/gokumui/ultimate_1_1.gif",
        "frames": 14,
        "frameWidth": 97,
        "frameHeight": 92,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": 0,
        "offsetY": 0,
        "centerY": 204
      },
      ULTIMATE_1_1: {
        "imageUrl": "/Assets/personagens/gokumui/ultimate_1_1.gif",
        "frames": 14,
        "frameWidth": 97,
        "frameHeight": 92,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": 0,
        "offsetY": 0,
        "centerY": 204,
        "zoomType": "ZOOM_IN",
        "zoomAmount": 4.45
      },
      ULTIMATE_1_2: {
        "imageUrl": "/Assets/personagens/gokumui/ultimate_1_2.gif",
        "frames": 2,
        "frameWidth": 141,
        "frameHeight": 72,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": -97,
        "offsetY": 0
      },
      ULTIMATE_1_3: {
        "imageUrl": "/Assets/personagens/gokumui/ultimate_1_3.gif",
        "frames": 8,
        "frameWidth": 158,
        "frameHeight": 88,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 0.7000000000000001,
        "offsetX": 10,
        "offsetY": 20,
        "zoomType": "IMMEDIATE",
        "zoomAmount": 1.5,
        "fullScreen": true
      },
      ULTIMATE_1_4: {
        "imageUrl": "/Assets/personagens/gokumui/ultimate_1_4.gif",
        "frames": 10,
        "frameWidth": 158,
        "frameHeight": 88,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 0.7,
        "offsetX": 10,
        "offsetY": 20,
        "fullScreen": true
      },
      ULTIMATE_1_5: {
        "imageUrl": "/Assets/personagens/gokumui/ultimate_1_5.gif",
        "frames": 21,
        "frameWidth": 186,
        "frameHeight": 161,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": 0,
        "offsetY": 0,
        "centerY": 263
      },
      ULTIMATE_1_6: {
        "imageUrl": "/Assets/personagens/gokumui/ultimate_1_6.gif",
        "frames": 11,
        "frameWidth": 57,
        "frameHeight": 149,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": -13,
        "offsetY": 0
      },
      ULTIMATE_1_7: {
        "imageUrl": "/Assets/personagens/gokumui/ultimate_1_7.gif",
        "frames": 24,
        "frameWidth": 162,
        "frameHeight": 92,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 0.8,
        "offsetX": 0,
        "offsetY": 8,
        "fullScreen": true,
        "zoomType": "IMMEDIATE",
        "zoomAmount": 1.5
      },
      ULTIMATE_1_8: {
        "imageUrl": "/Assets/personagens/gokumui/ultimate_1_8.gif",
        "frames": 8,
        "frameWidth": 48,
        "frameHeight": 50,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": 0,
        "offsetY": 0,
        "zoomType": "ZOOM_IN",
        "zoomAmount": 7.25,
        "cameraFocusX": 54,
        "cameraFocusY": 109
      },
      ULTIMATE_1_9: {
        "imageUrl": "/Assets/personagens/gokumui/ultimate_1_9.gif",
        "frames": 8,
        "frameWidth": 34,
        "frameHeight": 50,
        "isGif": true,
        "speed": 5,
        "loop": true,
        "scale": 2.2,
        "offsetX": 0,
        "offsetY": 0
      },

      [PlayerState.BLOCKING]: createGifAnim(URLS.defesa, true),
      Defesa_Agachado: createGifAnim(URLS.defesa_agachado, true),
      Defesa_Ar: createGifAnim(URLS.defesa_ar, true),

      [PlayerState.HIT]: createGifAnim(URLS.hit_light_1, false),
      [PlayerState.HIT_2]: createGifAnim(URLS.hit_medium_1, false),
      [PlayerState.HIT_3]: createGifAnim(URLS.hit_heavy_start, false),
      HIT_HIGH_LIGHT: createGifAnim(URLS.hit_light_1, false),
      HIT_HIGH_MEDIUM: createGifAnim(URLS.hit_medium_1, false),
      HIT_HIGH_HARD: createGifAnim(URLS.hit_heavy_start, false),
      HIT_LOW_LIGHT: createGifAnim(URLS.hit_light_2, false),
      HIT_LOW_HARD: createGifAnim(URLS.hit_medium_2, false),
      CROUCH_HIT: createGifAnim(URLS.hit_light_2, false),
      AIR_HIT: createGifAnim(URLS.hit_heavy_air, false),
      AIR_HIT_START: createGifAnim(URLS.hit_heavy_start, false),
      GROUND_BOUNCE: createGifAnim(URLS.caindo, false),
      FALL: createGifAnim(URLS.pulo, true),
      DOWN_LYING_DOWN: createGifAnim(URLS.aterrisando, true),
      [PlayerState.FALLING_HIT]: createGifAnim(URLS.hit_heavy_air, true),
      [PlayerState.FALLING_HIT_GROUND]: createGifAnim(URLS.aterrisando, false),
      LANDING_FALL: createGifAnim(URLS.aterrisando, false),
      GROUND_HIT: createGifAnim(URLS.caindo, false),
      [PlayerState.LAUNCHED]: createGifAnim(URLS.hit_heavy_start, false),
      [PlayerState.STUNNED]: createGifAnim(URLS.hit_medium_1, false),
      [PlayerState.GUARD_BREAK]: createGifAnim(URLS.hit_heavy_start, false),
      [PlayerState.KNOCKED_DOWN]: createGifAnim(URLS.caindo, false),
      [PlayerState.GROUND_RECOVERY]: createGifAnim(URLS.aterrisando, false),
      GET_UP_START: createGifAnim(URLS.aterrisando, false),
      GET_UP_MIDDLE: createGifAnim(URLS.aterrisando, false),
      GET_UP_END: createGifAnim(URLS.aterrisando, false),
      GET_UP: createGifAnim(URLS.aterrisando, false),
      GET_UP_AIR: createGifAnim(URLS.hit_light_3, false),
      LAUNCHED: createGifAnim(URLS.hit_heavy_air, true),

      [PlayerState.DASH_START]: createGifAnim(URLS.super_dash_1, false),
      [PlayerState.DASHING]: createGifAnim(URLS.super_dash_2, true),
      [PlayerState.DASH_END]: createGifAnim(URLS.super_dash_2, false),
      [PlayerState.MUI_DODGE]: createGifAnim(URLS.instinto, false),
      [PlayerState.VANISH]: createGifAnim(URLS.teleporte, false, 5),
      [PlayerState.VANISH_APPEAR]: createGifAnim(URLS.teleporte, false, 5),
      TELEPORT: createGifAnim(URLS.teleporte, false),
      TELEPORTE: createGifAnim(URLS.teleporte, false),
      [PlayerState.SUPER_DASH]: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_1: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_2: createGifAnim(URLS.super_dash_2, true, 5),
      super_dash_2: createGifAnim(URLS.super_dash_2, true, 5),
      [PlayerState.QUICK_DASH]: createGifAnim(URLS.double_tap, false),
      DOUBLE_TAP: createGifAnim(URLS.double_tap, false),
      [PlayerState.DRAGON_RUSH]: createGifAnim(URLS.dragon_rush_1, false),
      [PlayerState.DRAGON_COMBO]: createGifAnim(URLS.dragon_rush_2, false),
      [PlayerState.DRAGON_DASH_FOLLOW]: createGifAnim(URLS.dragon_rush_3, false),
      dragon_rush_2: createGifAnim(URLS.dragon_rush_2, false),
      dragon_rush_3: createGifAnim(URLS.dragon_rush_3, false),

      [PlayerState.CHARGE_START]: createGifAnim(URLS.carregando_ki_1, false),
      [PlayerState.CHARGING]: {
        imageUrl: URLS.carregando_ki_2,
        frames: 2,
        frameWidth: 31,
        frameHeight: 59,
        isGif: true,
        speed: 5,
        loop: true,
        scale: 2.2,
        offsetX: 0,
        offsetY: 0,
        auraConfigKey: "CHAVE_AURA_002"
      },
      [PlayerState.CHARGE_END]: createGifAnim(URLS.carregando_ki_3, false),
      [PlayerState.SPARKING]: createGifAnim(URLS.parado, false),
      [PlayerState.STANDBY]: createGifAnim(URLS.parado, true),
      TAG_IN_KO: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_IN]: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_OUT]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_ENTRY]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_EXIT]: createGifAnim(URLS.parado, false),
      [PlayerState.VICTORY]: createGifAnim(URLS.parado, false),
      [PlayerState.DEFEAT]: createGifAnim(URLS.hit_light_1, false),
      DETRANSFORM: createGifAnim(URLS.desfazendo_transformacao, false),
    },
  },

  skills: [
    {
      id: "mui_kamehameha",
      name: "Divindade Final",
      type: "PRIMARY",
      description: "Ataque supremo do Instinto Superior.",
    },
    {
      id: "mui_dodge",
      name: "Esquiva Instintiva",
      type: "EVO",
      description: "Esquiva automática do próximo ataque",
    },
  ],
};
