import { CharacterData, PlayerState } from "../types";
import { Kuririn_Beams } from "./beams/Kuririn_Beams";

const URLS = {
  agachado: "/Assets/personagens/kuririn/agachado.gif",
  aterrissagem: "/Assets/personagens/kuririn/aterrissagem.gif",
  caindo: "/Assets/personagens/kuririn/caindo.gif",
  carregando_ki_1: "/Assets/personagens/kuririn/carregando_ki_1.gif",
  carregando_ki_2: "/Assets/personagens/kuririn/carregando_ki_2.gif",
  carregando_ki_3: "/Assets/personagens/kuririn/carregando_ki_3.gif",
  combo_forte: "/Assets/personagens/kuririn/combo_forte.gif",
  combo_forte_ar: "/Assets/personagens/kuririn/combo_forte_ar.gif",

  hit_light_1: "/Assets/personagens/kuririn/hit_light_1_face_hit.png",
  hit_light_2: "/Assets/personagens/kuririn/hit_light_2_body_hit.png",
  hit_light_3: "/Assets/personagens/kuririn/hit_light_3_recoil.png",
  hit_medium_1: "/Assets/personagens/kuririn/hit_medium_1_stagger.png",
  hit_medium_2: "/Assets/personagens/kuririn/hit_medium_2_body_recoil.png",
  hit_medium_3: "/Assets/personagens/kuririn/hit_medium_3_knockback.png",
  hit_heavy_start: "/Assets/personagens/kuririn/hit_heavy_blowback_start.png",
  hit_heavy_air: "/Assets/personagens/kuririn/hit_heavy_blowback_air.png",

  defesa: "/Assets/personagens/kuririn/defesa.gif",
  defesa_agachado: "/Assets/personagens/kuririn/defesa_agachado.gif",
  defesa_ar: "/Assets/personagens/kuririn/defesa_ar.gif",
  double_tap: "/Assets/personagens/kuririn/double_tap.gif",
  dragon_rush_1: "/Assets/personagens/kuririn/dragon_rush_1.gif",
  dragon_rush_2: "/Assets/personagens/kuririn/dragon_rush_2.gif",
  dragon_rush_3: "/Assets/personagens/kuririn/dragon_rush_3.gif",
  entrada_por_ko: "/Assets/personagens/kuririn/entrada_por_ko.gif",
  especial_1_1: "/Assets/personagens/kuririn/especial_1_1.gif",
  especial_1_2: "/Assets/personagens/kuririn/especial_1_2.gif",
  especial_2_1: "/Assets/personagens/kuririn/especial_2_1.gif",
  especial_2_2: "/Assets/personagens/kuririn/especial_2_2.gif",
  especial_3_1: "/Assets/personagens/kuririn/especial_3_1.gif",
  especial_3_2: "/Assets/personagens/kuririn/especial_3_2.gif",
  especial_3_3: "/Assets/personagens/kuririn/especial_3_3.gif",
  especial_3_4: "/Assets/personagens/kuririn/especial_3_4.gif",
  especial_kiblast_1_1: "/Assets/personagens/kuririn/especial_kiblast_1_1.gif",
  especial_kiblast_1_2: "/Assets/personagens/kuririn/especial_kiblast_1_2.gif",
  especial_kiblast_ar_1_1: "/Assets/personagens/kuririn/especial_kiblast_ar_1_1.gif",
  especial_kiblast_ar_1_2: "/Assets/personagens/kuririn/especial_kiblast_ar_1_2.gif",
  especial_kiblast_ar_1_3: "/Assets/personagens/kuririn/especial_kiblast_ar_1_3.gif",
  frente: "/Assets/personagens/kuririn/frente.gif",
  introducao_1_1: "/Assets/personagens/kuririn/introducao_1_1.gif",
  introducao_1_2: "/Assets/personagens/kuririn/introducao_1_2.gif",
  introducao_1_3: "/Assets/personagens/kuririn/introducao_1_3.gif",
  introducao_1_4: "/Assets/personagens/kuririn/introducao_1_4.gif",
  introducao_1_5: "/Assets/personagens/kuririn/introducao_1_5.gif",
  introducao_1_6: "/Assets/personagens/kuririn/introducao_1_6.gif",
  introducao_1_7: "/Assets/personagens/kuririn/introducao_1_7.gif",
  parado: "/Assets/personagens/kuririn/parado.gif",
  pulo: "/Assets/personagens/kuririn/pulo.gif",
  sparking: "/Assets/personagens/kuririn/sparking.gif",
  super_dash_1: "/Assets/personagens/kuririn/super_dash_1.gif",
  super_dash_2: "/Assets/personagens/kuririn/super_dash_2.gif",
  teleporte: "/Assets/personagens/kuririn/teleporte.gif",
  tras: "/Assets/personagens/kuririn/tras.gif",
  ultimate_1_1: "/Assets/personagens/kuririn/ultimate_1_1.gif",
  ultimate_1_2: "/Assets/personagens/kuririn/ultimate_1_2.gif",
  ultimate_1_3: "/Assets/personagens/kuririn/ultimate_1_3.gif",
  ultimate_2_1: "/Assets/personagens/kuririn/ultimate_2_1.gif",
  ultimate_2_2: "/Assets/personagens/kuririn/ultimate_2_2.gif",
  ultimate_2_3: "/Assets/personagens/kuririn/ultimate_2_3.gif",
  ultimate_2_4: "/Assets/personagens/kuririn/ultimate_2_4.gif",
  ultimate_2_5: "/Assets/personagens/kuririn/ultimate_2_5.gif",
  ultimate_2_6: "/Assets/personagens/kuririn/ultimate_2_6.gif",
  ultimate_2_7: "/Assets/personagens/kuririn/ultimate_2_7.gif",
  ultimate_2_8: "/Assets/personagens/kuririn/ultimate_2_8.gif",
  ultimate_combinado_1_1: "/Assets/personagens/kuririn/ultimate_combinado_1_1.gif",
  ultimate_combinado_1_2: "/Assets/personagens/kuririn/ultimate_combinado_1_2.gif",
  ultimate_combinado_1_3: "/Assets/personagens/kuririn/ultimate_combinado_1_3.gif",
  ultimate_combinado_1_4: "/Assets/personagens/kuririn/ultimate_combinado_1_4.gif",
  ultimate_combinado_1_5: "/Assets/personagens/kuririn/ultimate_combinado_1_5.gif",
  ultimate_combinado_1_6: "/Assets/personagens/kuririn/ultimate_combinado_1_6.gif",
  ultimate_combinado_1_7: "/Assets/personagens/kuririn/ultimate_combinado_1_7.gif",
  ultimate_combinado_1_8: "/Assets/personagens/kuririn/ultimate_combinado_1_8.gif",
  ultimate_combinado_1_9: "/Assets/personagens/kuririn/ultimate_combinado_1_9.gif",
};

const DEFAULT_RPG = {
  level: 1,
  currentXp: 0,
  xpToNextLevel: 100,
  availablePoints: 0,
};

const createGifAnim = (url: string, loop: boolean = true, speed: number = 5) => ({
  imageUrl: url || "",
  frames: 1,
  frameWidth: 0,
  frameHeight: 0,
  isGif: true,
  speed,
  loop,
  scale: 2.2,
});

const createPngAnim = (url: string, loop: boolean = true, speed: number = 5) => ({
  imageUrl: url || "",
  frames: 1,
  frameWidth: 0,
  frameHeight: 0,
  isGif: false,
  speed,
  loop,
  scale: 2.2,
});

export const Kuririn: CharacterData = {
  id: "kuririn",
  name: "KURIRIN",
  color: "#f59e0b",
  rarity: "RARE",
  tags: ["HUMAN", "HERO", "Z_FIGHTER"],
  introText: "Eu vou dar o meu melhor!",
  stats: {
    attack: 9,
    defense: 9,
    speed: 12,
  },
  ...DEFAULT_RPG,
  beamOverrides: Kuririn_Beams,
  spriteConfig: {
    defaultScale: 2.2,
    portraitUrl: "/Assets/personagens/kuririn/prewiew.png",
    hitboxWidth: 49,
    hitboxHeight: 101,
    hitboxOffsetX: 35,
    hitboxOffsetY: 65,
    animations: {
      [PlayerState.INTRO]: createGifAnim(URLS.introducao_1_1, false),
      INTRO_1: {
        imageUrl: "/Assets/personagens/kuririn/introducao_1_1.gif",
        frames: 6,
        frameWidth: 81,
        frameHeight: 44,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 0.7999999999999997,
        offsetX: 0,
        offsetY: 50,
        zoomType: "IMMEDIATE",
        zoomAmount: 1.5,
        fullScreen: true
      },
      INTRO_2: {
        imageUrl: "/Assets/personagens/kuririn/introducao_1_2.gif",
        frames: 15,
        frameWidth: 81,
        frameHeight: 44,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 1.0999999999999999,
        offsetX: 0,
        offsetY: 50,
        zoomType: "IMMEDIATE",
        zoomAmount: 1.5,
        fullScreen: true
      },
      INTRO_3: createGifAnim(URLS.introducao_1_3, false),
      INTRO_4: {
        imageUrl: "/Assets/personagens/kuririn/introducao_1_4.gif",
        frames: 7,
        frameWidth: 62,
        frameHeight: 42,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 0.6000000000000001,
        offsetX: -20,
        offsetY: 78,
        zoomType: "IMMEDIATE",
        zoomAmount: 1.5,
        fullScreen: true
      },
      INTRO_5: {
        imageUrl: "/Assets/personagens/kuririn/introducao_1_5.gif",
        frames: 9,
        frameWidth: 87,
        frameHeight: 46,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 2.2,
        offsetX: 0,
        offsetY: 0,
        zoomType: "ZOOM_IN",
        zoomAmount: 3.8
      },
      INTRO_6: {
        imageUrl: "/Assets/personagens/kuririn/introducao_1_6.gif",
        frames: 2,
        frameWidth: 108,
        frameHeight: 90,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 0.6000000000000001,
        offsetX: -11,
        offsetY: 40,
        zoomType: "IMMEDIATE",
        zoomAmount: 1.5,
        fullScreen: true
      },
      INTRO_7: {
        imageUrl: "/Assets/personagens/kuririn/introducao_1_7.gif",
        frames: 3,
        frameWidth: 107,
        frameHeight: 90,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 0.6000000000000001,
        offsetX: -10,
        offsetY: 39,
        zoomType: "IMMEDIATE",
        zoomAmount: 1.5,
        fullScreen: true
      },

      [PlayerState.IDLE]: createGifAnim(URLS.parado, true),
      [PlayerState.WALK_BACKWARD]: createGifAnim(URLS.tras, true),
      [PlayerState.RUNNING]: createGifAnim(URLS.frente, true),
      [PlayerState.DASH_START]: createGifAnim(URLS.super_dash_1, false),
      [PlayerState.DASHING]: createGifAnim(URLS.super_dash_2, true),
      [PlayerState.DASH_END]: createGifAnim(URLS.super_dash_2, false),
      [PlayerState.CROUCH]: createGifAnim(URLS.agachado, true),
      [PlayerState.JUMPING]: createGifAnim(URLS.pulo, false),
      [PlayerState.FALLING]: createGifAnim(URLS.pulo, true),
      FALLING_LOOP: createGifAnim(URLS.pulo, true),
      [PlayerState.LANDING]: createGifAnim(URLS.aterrissagem, false),

      [PlayerState.BLOCKING]: createGifAnim(URLS.defesa, false),
      [PlayerState.BLOCKING_CROUCH]: createGifAnim(URLS.defesa_agachado, false),
      [PlayerState.BLOCKING_AIR]: createGifAnim(URLS.defesa_ar, false),

      [PlayerState.CHARGE_START]: createGifAnim(URLS.carregando_ki_1, false),
      [PlayerState.CHARGING]: {
        imageUrl: URLS.carregando_ki_2,
        frames: 1,
        frameWidth: 29,
        frameHeight: 34,
        isGif: true,
        speed: 5,
        loop: true,
        scale: 2.2,
        offsetX: 0,
        offsetY: 0,
        auraConfigKey: "CHAVE_AURA_004"
      },
      [PlayerState.CHARGE_END]: createGifAnim(URLS.carregando_ki_3, false),

      [PlayerState.HIT]: createGifAnim(URLS.hit_light_1, false),
      [PlayerState.HIT_2]: createGifAnim(URLS.hit_medium_1, false),
      [PlayerState.HIT_3]: createGifAnim(URLS.hit_heavy_start, false),
      HIT_HIGH_LIGHT: createGifAnim(URLS.hit_light_1, false),
      HIT_HIGH_MEDIUM: createGifAnim(URLS.hit_medium_1, false),
      HIT_HIGH_HARD: createGifAnim(URLS.hit_heavy_start, false),
      HIT_LOW_LIGHT: createGifAnim(URLS.hit_light_2, false),
      HIT_LOW_HARD: createGifAnim(URLS.hit_medium_2, false),
      CROUCH_HIT: createGifAnim(URLS.hit_light_2, false),
      AIR_HIT: createGifAnim(URLS.hit_heavy_air, false),
      AIR_HIT_START: createGifAnim(URLS.hit_heavy_start, false),
      GROUND_BOUNCE: createGifAnim(URLS.caindo, false),
      FALL: createGifAnim(URLS.pulo, true),
      DOWN_LYING_DOWN: createGifAnim(URLS.aterrissagem, true),
      [PlayerState.FALLING_HIT]: createGifAnim(URLS.hit_heavy_air, true),
      [PlayerState.FALLING_HIT_GROUND]: createGifAnim(URLS.aterrissagem, false),
      LANDING_FALL: createGifAnim(URLS.aterrissagem, false),
      GROUND_HIT: createGifAnim(URLS.caindo, false),
      [PlayerState.LAUNCHED]: createGifAnim(URLS.hit_heavy_start, false),
      [PlayerState.STUNNED]: createGifAnim(URLS.hit_medium_1, false),
      [PlayerState.GUARD_BREAK]: createGifAnim(URLS.hit_heavy_start, false),
      [PlayerState.KNOCKED_DOWN]: createGifAnim(URLS.caindo, false),
      [PlayerState.GROUND_RECOVERY]: createGifAnim(URLS.aterrissagem, false),
      GET_UP_START: createGifAnim(URLS.aterrissagem, false),
      GET_UP_MIDDLE: createGifAnim(URLS.aterrissagem, false),
      GET_UP_END: createGifAnim(URLS.aterrissagem, false),
      GET_UP: createGifAnim(URLS.aterrissagem, false),
      GET_UP_AIR: createGifAnim(URLS.hit_light_3, false),
      LAUNCHED: createGifAnim(URLS.hit_heavy_air, true),

      [PlayerState.VANISH]: createGifAnim(URLS.teleporte, false),
      [PlayerState.VANISH_APPEAR]: createGifAnim(URLS.teleporte, false),
      TELEPORT: createGifAnim(URLS.teleporte, false),
      TELEPORTE: createGifAnim(URLS.teleporte, false),

      [PlayerState.SUPER_DASH]: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_1: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_2: createGifAnim(URLS.super_dash_2, true, 5),
      super_dash_2: createGifAnim(URLS.super_dash_2, true, 5),
      [PlayerState.QUICK_DASH]: createGifAnim(URLS.double_tap, false),
      DOUBLE_TAP: createGifAnim(URLS.double_tap, false),
      [PlayerState.DRAGON_RUSH]: createGifAnim(URLS.dragon_rush_1, false),
      [PlayerState.DRAGON_COMBO]: createGifAnim(URLS.dragon_rush_2, false),
      [PlayerState.DRAGON_DASH_FOLLOW]: createGifAnim(URLS.dragon_rush_3, false),
      dragon_rush_2: createGifAnim(URLS.dragon_rush_2, false),
      dragon_rush_3: createGifAnim(URLS.dragon_rush_3, false),

      KI_BLAST_1: createGifAnim(URLS.especial_kiblast_1_1, false),
      KI_BLAST_2: createGifAnim(URLS.especial_kiblast_1_2, false),
      KI_BLAST_3: createGifAnim(URLS.especial_kiblast_1_1, false),
      KI_BLAST_4: createGifAnim(URLS.especial_kiblast_1_2, false),

      KI_BLAST_AR_1: createGifAnim(URLS.especial_kiblast_ar_1_1, false),
      KI_BLAST_AR_2: createGifAnim(URLS.especial_kiblast_ar_1_2, false),
      KI_BLAST_AR_3: createGifAnim(URLS.especial_kiblast_ar_1_3, false),

      Especial_1_1: {
        "imageUrl": "/Assets/personagens/kuririn/especial_1_1.gif",
        "frames": 10,
        "frameWidth": 128,
        "frameHeight": 116,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": -10,
        "offsetY": 84
      },
      Especial_1_2: {
        ...createGifAnim(URLS.especial_1_2, false),
        createsBeam: "CHAVE_BEAM_006",
        effectConfigKey: "CHAVE_EFFECT_TELACHEIA_05_AZUL"
      },

      Especial_2_1: createGifAnim(URLS.especial_2_1, false),
      Especial_2_2: createGifAnim(URLS.especial_2_2, false),

      Especial_3_1: {
        "imageUrl": "/Assets/personagens/kuririn/especial_3_1.gif",
        "frames": 10,
        "frameWidth": 78,
        "frameHeight": 78,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": 13,
        "offsetY": 0
      },
      Especial_3_2: createGifAnim(URLS.especial_3_2, false),
      Especial_3_3: {
        "imageUrl": "/Assets/personagens/kuririn/especial_3_3.gif",
        "frames": 3,
        "frameWidth": 76,
        "frameHeight": 68,
        "isGif": true,
        "speed": 5,
        "loop": false,
        "scale": 2.2,
        "offsetX": -22,
        "offsetY": 0
      },
      Especial_3_4: createGifAnim(URLS.especial_3_4, false),

      ULTIMATE_1_1: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_1_1.gif",
        frames: 3,
        frameWidth: 80,
        frameHeight: 147,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 2.2,
        offsetX: 0,
        offsetY: 184
      },
      ULTIMATE_1_2: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_1_2.gif",
        frames: 12,
        frameWidth: 131,
        frameHeight: 131,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 2.2,
        offsetX: 0,
        offsetY: 111
      },
      ULTIMATE_1_3: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_1_3.gif",
        frames: 11,
        frameWidth: 426,
        frameHeight: 426,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 2.2,
        offsetX: -6,
        offsetY: 438
      },

      ULTIMATE_2_1: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_2_1.gif",
        frames: 5,
        frameWidth: 34,
        frameHeight: 37,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 2.2,
        offsetX: 0,
        offsetY: 0,
        zoomType: "ZOOM_IN",
        zoomAmount: 6.4,
        cameraFocusX: 50,
        cameraFocusY: 130
      },
      ULTIMATE_2_2: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_2_2.gif",
        frames: 8,
        frameWidth: 72,
        frameHeight: 61,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 2.2,
        offsetX: 50,
        offsetY: 0,
        zoomType: "ZOOM_IN",
        zoomAmount: 2.15,
        fullScreen: false
      },
      ULTIMATE_2_3: {
        ...createGifAnim(URLS.ultimate_2_3, false),
        createsBeam: "CHAVE_BEAM_008"
      },
      ULTIMATE_2_4: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_2_4.gif",
        frames: 5,
        frameWidth: 81,
        frameHeight: 44,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 2,
        offsetX: 0,
        offsetY: 46,
        fullScreen: true,
        zoomType: "IMMEDIATE",
        zoomAmount: 1.5
      },
      ULTIMATE_2_5: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_2_5.gif",
        frames: 20,
        frameWidth: 81,
        frameHeight: 44,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 2.2,
        offsetX: 0,
        offsetY: 0,
        fullScreen: true,
        zoomType: "IMMEDIATE",
        zoomAmount: 1.5
      },
      ULTIMATE_2_6: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_2_6.gif",
        frames: 9,
        frameWidth: 160,
        frameHeight: 90,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 0.30000000000000004,
        offsetX: 0,
        offsetY: 30,
        fullScreen: true,
        zoomType: "IMMEDIATE",
        zoomAmount: 1.5
      },
      ULTIMATE_2_7: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_2_7.gif",
        frames: 6,
        frameWidth: 96,
        frameHeight: 90,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 0.9,
        offsetX: 0,
        offsetY: 50,
        zoomType: "ZOOM_IN",
        zoomAmount: 1.5,
        fullScreen: true
      },
      ULTIMATE_2_8: createGifAnim(URLS.ultimate_2_8, false),

      ULTIMATE_3_1: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_combinado_1_1.gif",
        frames: 6,
        frameWidth: 41,
        frameHeight: 48,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 2.2,
        offsetX: 0,
        offsetY: 0,
        zoomType: "ZOOM_IN",
        zoomAmount: 3
      },
      ULTIMATE_3_2: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_combinado_1_2.gif",
        frames: 14,
        frameWidth: 120,
        frameHeight: 67,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 0.7999999999999999,
        offsetX: 0,
        offsetY: 30,
        zoomType: "IMMEDIATE",
        zoomAmount: 1.5,
        fullScreen: true
      },
      ULTIMATE_3_3: createGifAnim(URLS.ultimate_combinado_1_3, false),
      ULTIMATE_3_4: createGifAnim(URLS.ultimate_combinado_1_4, false),
      ULTIMATE_3_5: createGifAnim(URLS.ultimate_combinado_1_5, false),
      ULTIMATE_3_6: createGifAnim(URLS.ultimate_combinado_1_6, false),
      ULTIMATE_3_7: createGifAnim(URLS.ultimate_combinado_1_7, false),
      ULTIMATE_3_8: {
        imageUrl: "/Assets/personagens/kuririn/ultimate_combinado_1_8.gif",
        frames: 12,
        frameWidth: 138,
        frameHeight: 140,
        isGif: true,
        speed: 5,
        loop: false,
        scale: 2.2,
        offsetX: 0,
        offsetY: 80,
        zoomType: "ZOOM_IN",
        zoomAmount: 3.5,
        cameraFocusY: 110,
        cameraFocusX: 60
      },
      ULTIMATE_3_9: {
        ...createGifAnim(URLS.ultimate_combinado_1_9, false),
        createsBeam: "CHAVE_BEAM_003"
      },

      [PlayerState.SPARKING]: createGifAnim(URLS.sparking, true),
      [PlayerState.STANDBY]: createGifAnim(URLS.parado, true),
      TAG_IN_KO: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_IN]: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_OUT]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_ENTRY]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_EXIT]: createGifAnim(URLS.parado, false),
      [PlayerState.VICTORY]: createGifAnim(URLS.parado, false),
    }
  },
  skills: [], // Adicionado para satisfazer a interface CharacterData se necessário
};
