import { CharacterData, PlayerState } from '../types';
import { TeenGohanSSJ2_Beams } from './beams/TeenGohanSSJ2_Beams';

const BASE_URL = "/Assets/personagens/teengohanssj2/";

const URLS = {
  agachado: `${BASE_URL}agachado.gif`,
  aterrissagem: `${BASE_URL}aterrissagem.gif`,
  caindo: `${BASE_URL}caindo.gif`,
  carregando_ki_1: `${BASE_URL}carregando_ki_1.gif`,
  carregando_ki_2: `${BASE_URL}carregando_ki_2.gif`,
  carregando_ki_3: `${BASE_URL}carregando_ki_3.gif`,
  dano_1: `${BASE_URL}caindo.gif`,
  defesa: `${BASE_URL}defesa.gif`,
  defesa_agachado: `${BASE_URL}defesa_agachado.gif`,
  defesa_ar: `${BASE_URL}defesa_ar.gif`,
  double_tap: `${BASE_URL}double_tap.gif`,
  dragon_rush_1: `${BASE_URL}dragon_rush_1.gif`,
  dragon_rush_2: `${BASE_URL}dragon_rush_2.gif`,
  dragon_rush_3: `${BASE_URL}dragon_rush_3.gif`,
  especial_1_1: `${BASE_URL}especial_1_1.gif`,
  especial_1_2: `${BASE_URL}especial_1_2.gif`,
  especial_2_1: `${BASE_URL}especial_2_1.gif`,
  especial_2_2: `${BASE_URL}especial_2_2.gif`,
  especial_3_1: `${BASE_URL}especial_3_1.gif`,
  especial_3_2: `${BASE_URL}especial_3_2.gif`,
  especial_3_3: `${BASE_URL}especial_3_3.gif`,
  especial_kiblast_1: `${BASE_URL}especial_kiblast_1.gif`,
  especial_kiblast_2: `${BASE_URL}especial_kiblast_2.gif`,
  frente: `${BASE_URL}frente.gif`,
  introducao_1_1: `${BASE_URL}introducao_1_1.gif`,
  introducao_1_2: `${BASE_URL}introducao_1_2.gif`,
  introducao_1_3: `${BASE_URL}introducao_1_3.gif`,
  introducao_1_4: `${BASE_URL}introducao_1_4.gif`,
  introducao_1_5: `${BASE_URL}introducao_1_5.gif`,
  introducao_1_6: `${BASE_URL}introducao_1_6.gif`,
  introducao_1_7: `${BASE_URL}introducao_1_7.gif`,
  parado: `${BASE_URL}parado.gif`,
  pulo: `${BASE_URL}pulo.gif`,
  super_dash_1: `${BASE_URL}super_dash_1.gif`,
  super_dash_2: `${BASE_URL}super_dash_2.gif`,
  tras: `${BASE_URL}tras.gif`,
  ultimate_2_parte1_1: `${BASE_URL}ultimate_2_parte1_1.gif`,
  ultimate_2_parte1_2: `${BASE_URL}ultimate_2_parte1_2.gif`,
  ultimate_2_parte1_3: `${BASE_URL}ultimate_2_parte1_3.gif`,
  ultimate_2_parte1_4: `${BASE_URL}ultimate_2_parte1_4.gif`,
  ultimate_2_parte2_1: `${BASE_URL}ultimate_2_parte2_1.gif`,
  ultimate_2_parte2_2: `${BASE_URL}ultimate_2_parte2_2.gif`,
  ultimate_2_parte2_3: `${BASE_URL}ultimate_2_parte2_3.gif`,
};

const createGifAnim = (url: string, loop: boolean = true, speed: number = 5) => ({
  imageUrl: url,
  frames: 1,
  frameWidth: 0,
  frameHeight: 0,
  isGif: true,
  speed,
  loop,
  scale: 2.2,
});

export const TeenGohanSSJ2: CharacterData = {
  id: "teen_gohan_ssj2",
  name: "TEEN GOHAN SSJ2",
  color: "#a855f7",
  rarity: "EPIC",
  tags: ["SAIYAN", "HERO", "HYBRID"],
  transformTo: [],
  detransformTo: [],
  beamOverrides: TeenGohanSSJ2_Beams,
  introText: "Eu não vou deixar você machucar mais ninguém!",
  stats: {
    attack: 16,
    defense: 13,
    speed: 16,
  },
  level: 1,
  currentXp: 0,
  xpToNextLevel: 100,
  availablePoints: 0,
  spriteConfig: {
    defaultScale: 2.2,
    portraitUrl: `${BASE_URL}prewiew.png`,
    hitboxWidth: 49,
    hitboxHeight: 90,
    hitboxOffsetX: 26,
    hitboxOffsetY: 70,
    animations: {
      [PlayerState.INTRO]: createGifAnim(URLS.introducao_1_1, false),
      INTRO_1: createGifAnim(URLS.introducao_1_1, false),
      INTRO_2: createGifAnim(URLS.introducao_1_2, false),
      INTRO_3: createGifAnim(URLS.introducao_1_3, false),
      INTRO_4: createGifAnim(URLS.introducao_1_4, false),
      INTRO_5: createGifAnim(URLS.introducao_1_5, false),
      INTRO_6: createGifAnim(URLS.introducao_1_6, false),
      INTRO_7: createGifAnim(URLS.introducao_1_7, false),

      [PlayerState.IDLE]: createGifAnim(URLS.parado, true),
      [PlayerState.RUNNING]: createGifAnim(URLS.frente, true),
      [PlayerState.WALK_BACKWARD]: createGifAnim(URLS.tras, true),
      [PlayerState.DASH_START]: createGifAnim(URLS.super_dash_1, false),
      [PlayerState.DASHING]: createGifAnim(URLS.super_dash_2, true),
      [PlayerState.DASH_END]: createGifAnim(URLS.super_dash_2, false),
      [PlayerState.CROUCH]: createGifAnim(URLS.agachado, true),
      [PlayerState.JUMPING]: createGifAnim(URLS.pulo, false),
      [PlayerState.FALLING]: createGifAnim(URLS.pulo, true),
      FALLING_LOOP: createGifAnim(URLS.pulo, true),
      [PlayerState.LANDING]: createGifAnim(URLS.aterrissagem, false),
      GROUND_HIT: createGifAnim(URLS.dano_1, false),
      GROUND_BOUNCE: createGifAnim(URLS.dano_1, false),
      FALL: createGifAnim(URLS.pulo, true),
      [PlayerState.FALLING_HIT]: createGifAnim(URLS.dano_1, true),
      [PlayerState.FALLING_HIT_GROUND]: createGifAnim(URLS.dano_1, false),

      [PlayerState.CHARGE_START]: createGifAnim(URLS.carregando_ki_1, false),
      [PlayerState.CHARGING]: {
        ...createGifAnim(URLS.carregando_ki_2, true),
        auraConfigKey: "CHAVE_AURA_007"
      },
      [PlayerState.CHARGE_END]: createGifAnim(URLS.carregando_ki_3, false),

      [PlayerState.BLOCKING]: createGifAnim(URLS.defesa, false),
      [PlayerState.BLOCKING_CROUCH]: createGifAnim(URLS.defesa_agachado, false),
      [PlayerState.BLOCKING_AIR]: createGifAnim(URLS.defesa_ar, false),

      [PlayerState.HIT]: createGifAnim(URLS.dano_1, false),
      [PlayerState.HIT_2]: createGifAnim(URLS.dano_1, false),
      [PlayerState.HIT_3]: createGifAnim(URLS.dano_1, false),
      [PlayerState.STUNNED]: createGifAnim(URLS.dano_1, false),
      [PlayerState.GUARD_BREAK]: createGifAnim(URLS.dano_1, false),
      [PlayerState.KNOCKED_DOWN]: createGifAnim(URLS.dano_1, false),
      [PlayerState.DEFEAT]: createGifAnim(URLS.dano_1, false),

      [PlayerState.VANISH]: createGifAnim(URLS.double_tap, false),
      [PlayerState.VANISH_APPEAR]: createGifAnim(URLS.double_tap, false),
      TELEPORT: createGifAnim(URLS.double_tap, false),
      TELEPORTE: createGifAnim(URLS.double_tap, false),

      [PlayerState.SUPER_DASH]: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_1: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_2: createGifAnim(URLS.super_dash_2, true, 5),
      super_dash_2: createGifAnim(URLS.super_dash_2, true, 5),

      [PlayerState.QUICK_DASH]: createGifAnim(URLS.double_tap, false),
      [PlayerState.DRAGON_RUSH]: createGifAnim(URLS.dragon_rush_1, false),
      [PlayerState.DRAGON_COMBO]: createGifAnim(URLS.dragon_rush_2, false),
      [PlayerState.DRAGON_DASH_FOLLOW]: createGifAnim(URLS.dragon_rush_3, false),
      dragon_rush_2: createGifAnim(URLS.dragon_rush_2, false),
      dragon_rush_3: createGifAnim(URLS.dragon_rush_3, false),

      KI_BLAST_1: createGifAnim(URLS.especial_kiblast_1, false),
      KI_BLAST_2: createGifAnim(URLS.especial_kiblast_2, false),

      Especial_1_1: createGifAnim(URLS.especial_1_1, false),
      Especial_1_2: {
        ...createGifAnim(URLS.especial_1_2, false),
        createsBeam: "CHAVE_BEAM_039"
      },
      Especial_2_1: createGifAnim(URLS.especial_2_1, false),
      Especial_2_2: {
        ...createGifAnim(URLS.especial_2_2, false),
        createsBeam: "CHAVE_BEAM_026"
      },
      Especial_3_1: createGifAnim(URLS.especial_3_1, false),
      Especial_3_2: createGifAnim(URLS.especial_3_2, false),
      Especial_3_3: createGifAnim(URLS.especial_3_3, false),

      Ultimate_2_1: createGifAnim(URLS.ultimate_2_parte1_1, false),
      Ultimate_2_2: createGifAnim(URLS.ultimate_2_parte1_2, false),
      Ultimate_2_3: createGifAnim(URLS.ultimate_2_parte1_3, false),
      Ultimate_2_4: createGifAnim(URLS.ultimate_2_parte1_4, false),
      Ultimate_2_5: createGifAnim(URLS.ultimate_2_parte2_1, false),
      Ultimate_2_6: createGifAnim(URLS.ultimate_2_parte2_2, false),
      Ultimate_2_7: createGifAnim(URLS.ultimate_2_parte2_3, false),
      [PlayerState.STANDBY]: createGifAnim(URLS.parado, true),
      TAG_IN_KO: createGifAnim(URLS.introducao_1_1, false),
      [PlayerState.TAG_IN]: createGifAnim(URLS.introducao_1_1, false),
      [PlayerState.TAG_OUT]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_ENTRY]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_EXIT]: createGifAnim(URLS.parado, false),
      [PlayerState.VICTORY]: createGifAnim(URLS.parado, false),
      [PlayerState.SPARKING]: createGifAnim(URLS.parado, false), // fallback or generic
    }
  }
};
