import { CharacterData, PlayerState } from '../types';

const BASE_URL = "/Assets/personagens/trunksssj2/";

const URLS = {
  agachado: `${BASE_URL}agachado.gif`,
  aterrissagem: `${BASE_URL}aterrissagem.gif`,
  caindo: `${BASE_URL}caindo.gif`,
  carregando_ki_1: `${BASE_URL}carregando_ki_1.gif`,
  carregando_ki_2: `${BASE_URL}carregando_ki_2.gif`,
  carregando_ki_3: `${BASE_URL}carregando_ki_3.gif`,
  dano_1: `${BASE_URL}dano_1.gif`,
  dano_2: `${BASE_URL}dano_2.gif`,
  dano_3: `${BASE_URL}dano_3.gif`,
  dano_4: `${BASE_URL}dano_4.gif`,
  defesa: `${BASE_URL}defesa.gif`,
  defesa_agachado: `${BASE_URL}defesa_agachado.gif`,
  defesa_ar: `${BASE_URL}defesa_ar.gif`,
  double_tap: `${BASE_URL}double_tap.gif`,
  dragon_rush_1: `${BASE_URL}dragon_rush_1.gif`,
  dragon_rush_2: `${BASE_URL}dragon_rush_2.gif`,
  dragon_rush_3: `${BASE_URL}dragon_rush_3.gif`,
  entrada_por_ko: `${BASE_URL}entrada_por_ko.gif`,
  especial_1_1: `${BASE_URL}especial_1_1.gif`,
  especial_1_2: `${BASE_URL}especial_1_2.gif`,
  especial_2_1: `${BASE_URL}especial_2_1.gif`,
  especial_2_2: `${BASE_URL}especial_2_2.gif`,
  especial_kiblast_1: `${BASE_URL}especial_kiblast_1.gif`,
  especial_kiblast_2: `${BASE_URL}especial_kiblast_2.gif`,
  frente: `${BASE_URL}frente.gif`,
  introducao_1_1: `${BASE_URL}introducao_1_1.gif`,
  introducao_1_2: `${BASE_URL}introducao_1_2.gif`,
  introducao_1_3: `${BASE_URL}introducao_1_3.gif`,
  introducao_1_4: `${BASE_URL}introducao_1_4.gif`,
  introducao_1_5: `${BASE_URL}introducao_1_5.gif`,
  parado: `${BASE_URL}parado.gif`,
  pulo: `${BASE_URL}pulo.gif`,
  sparking: `${BASE_URL}sparking.gif`,
  super_dash_1: `${BASE_URL}super_dash_1.gif`,
  super_dash_2: `${BASE_URL}super_dash_2.gif`,
  tras: `${BASE_URL}tras.gif`,
  ultimate_1_1: `${BASE_URL}ultimate_1_1.gif`,
  ultimate_1_2: `${BASE_URL}ultimate_1_2.gif`,
  ultimate_1_3: `${BASE_URL}ultimate_1_3.gif`,
  ultimate_1_4: `${BASE_URL}ultimate_1_4.gif`,
  ultimate_2_1: `${BASE_URL}ultimate_2_1.gif`,
  ultimate_2_2: `${BASE_URL}ultimate_2_2.gif`,
  ultimate_2_3: `${BASE_URL}ultimate_2_3.gif`,
  ultimate_2_4: `${BASE_URL}ultimate_2_4.gif`,
  ultimate_2_5: `${BASE_URL}ultimate_2_5.gif`,
  ultimate_2_6: `${BASE_URL}ultimate_2_6.gif`,
  ultimate_2_7: `${BASE_URL}ultimate_2_7.gif`,
  ultimate_2_8: `${BASE_URL}ultimate_2_8.gif`,
  ultimate_2_9: `${BASE_URL}ultimate_2_9.gif`,
  ultimate_2_10: `${BASE_URL}ultimate_2_10.gif`,
  ultimate_2_11: `${BASE_URL}ultimate_2_11.gif`,
  ultimate_2_12: `${BASE_URL}ultimate_2_12.gif`,
};

const createGifAnim = (url: string, loop: boolean = true, speed: number = 5) => ({
  imageUrl: url,
  frames: 1,
  frameWidth: 0,
  frameHeight: 0,
  isGif: true,
  speed,
  loop,
  scale: 2.2,
});

export const TrunksSSJ2: CharacterData = {
  id: "trunks_ssj2",
  name: "TRUNKS SSJ2",
  color: "#a855f7",
  rarity: "RARE",
  tags: ["SAIYAN", "HERO", "HYBRID", "FUTURE"],
  transformTo: [],
  detransformTo: [],
  introText: "Eu mudei o futuro!",
  stats: {
    attack: 13,
    defense: 12,
    speed: 14,
  },
  level: 1,
  currentXp: 0,
  xpToNextLevel: 100,
  availablePoints: 0,
  spriteConfig: {
    defaultScale: 2.2,
    portraitUrl: `${BASE_URL}prewiew.png`,
    hitboxWidth: 49,
    hitboxHeight: 101,
    hitboxOffsetX: 26,
    hitboxOffsetY: 79,
    animations: {
      [PlayerState.INTRO]: createGifAnim(URLS.introducao_1_1, false),
      INTRO_1: createGifAnim(URLS.introducao_1_1, false),
      INTRO_2: createGifAnim(URLS.introducao_1_2, false),
      INTRO_3: createGifAnim(URLS.introducao_1_3, false),
      INTRO_4: createGifAnim(URLS.introducao_1_4, false),
      INTRO_5: createGifAnim(URLS.introducao_1_5, false),

      [PlayerState.IDLE]: createGifAnim(URLS.parado, true),
      [PlayerState.RUNNING]: createGifAnim(URLS.frente, true),
      [PlayerState.WALK_BACKWARD]: createGifAnim(URLS.tras, true),
      [PlayerState.DASH_START]: createGifAnim(URLS.super_dash_1, false),
      [PlayerState.DASHING]: createGifAnim(URLS.super_dash_2, true),
      [PlayerState.DASH_END]: createGifAnim(URLS.super_dash_2, false),
      [PlayerState.CROUCH]: createGifAnim(URLS.agachado, true),
      [PlayerState.JUMPING]: createGifAnim(URLS.pulo, false),
      [PlayerState.FALLING]: createGifAnim(URLS.pulo, true),
      FALLING_LOOP: createGifAnim(URLS.pulo, true),
      [PlayerState.LANDING]: createGifAnim(URLS.aterrissagem, false),
      GROUND_HIT: createGifAnim(URLS.dano_1, false),
      GROUND_BOUNCE: createGifAnim(URLS.dano_1, false),
      FALL: createGifAnim(URLS.pulo, true),
      [PlayerState.FALLING_HIT]: createGifAnim(URLS.dano_1, true),
      [PlayerState.FALLING_HIT_GROUND]: createGifAnim(URLS.dano_1, false),

      [PlayerState.CHARGE_START]: createGifAnim(URLS.carregando_ki_1, false),
      [PlayerState.CHARGING]: {
        imageUrl: URLS.carregando_ki_2,
        frames: 2,
        frameWidth: 37,
        frameHeight: 60,
        isGif: true,
        speed: 5,
        loop: true,
        scale: 2.2,
        offsetX: 0,
        offsetY: 0,
        auraConfigKey: "CHAVE_AURA_010"
      },
      [PlayerState.CHARGE_END]: createGifAnim(URLS.carregando_ki_3, false),

      [PlayerState.BLOCKING]: createGifAnim(URLS.defesa, false),
      [PlayerState.BLOCKING_CROUCH]: createGifAnim(URLS.defesa_agachado, false),
      [PlayerState.BLOCKING_AIR]: createGifAnim(URLS.defesa_ar, false),

      [PlayerState.HIT]: createGifAnim(URLS.dano_1, false),
      [PlayerState.HIT_2]: createGifAnim(URLS.dano_2, false),
      [PlayerState.HIT_3]: createGifAnim(URLS.dano_3, false),
      DANO_4: createGifAnim(URLS.dano_4, false),
      [PlayerState.STUNNED]: createGifAnim(URLS.dano_1, false),
      [PlayerState.GUARD_BREAK]: createGifAnim(URLS.dano_1, false),
      [PlayerState.KNOCKED_DOWN]: createGifAnim(URLS.dano_1, false),
      [PlayerState.DEFEAT]: createGifAnim(URLS.dano_4, false),

      [PlayerState.SPARKING]: createGifAnim(URLS.sparking, true),
      [PlayerState.VANISH]: createGifAnim(URLS.double_tap, false),
      [PlayerState.VANISH_APPEAR]: createGifAnim(URLS.double_tap, false),
      TELEPORT: createGifAnim(URLS.double_tap, false),
      TELEPORTE: createGifAnim(URLS.double_tap, false),

      [PlayerState.SUPER_DASH]: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_1: createGifAnim(URLS.super_dash_1, true, 5),
      SUPER_DASH_2: createGifAnim(URLS.super_dash_2, true, 5),
      super_dash_2: createGifAnim(URLS.super_dash_2, true, 5),

      [PlayerState.QUICK_DASH]: createGifAnim(URLS.double_tap, false),
      [PlayerState.DRAGON_RUSH]: createGifAnim(URLS.dragon_rush_1, false),
      [PlayerState.DRAGON_COMBO]: createGifAnim(URLS.dragon_rush_2, false),
      [PlayerState.DRAGON_DASH_FOLLOW]: createGifAnim(URLS.dragon_rush_3, false),
      dragon_rush_2: createGifAnim(URLS.dragon_rush_2, false),
      dragon_rush_3: createGifAnim(URLS.dragon_rush_3, false),

      KI_BLAST_1: createGifAnim(URLS.especial_kiblast_1, false),
      KI_BLAST_2: createGifAnim(URLS.especial_kiblast_2, false),

      Especial_1_1: createGifAnim(URLS.especial_1_1, false),
      Especial_1_2: createGifAnim(URLS.especial_1_2, false),
      Especial_2_1: createGifAnim(URLS.especial_2_1, false),
      Especial_2_2: createGifAnim(URLS.especial_2_2, false),

      Ultimate_1_1: createGifAnim(URLS.ultimate_1_1, false),
      Ultimate_1_2: createGifAnim(URLS.ultimate_1_2, false),
      Ultimate_1_3: createGifAnim(URLS.ultimate_1_3, false),
      Ultimate_1_4: createGifAnim(URLS.ultimate_1_4, false),

      Ultimate_2_1: createGifAnim(URLS.ultimate_2_1, false),
      Ultimate_2_2: createGifAnim(URLS.ultimate_2_2, false),
      Ultimate_2_3: createGifAnim(URLS.ultimate_2_3, false),
      Ultimate_2_4: createGifAnim(URLS.ultimate_2_4, false),
      Ultimate_2_5: createGifAnim(URLS.ultimate_2_5, false),
      Ultimate_2_6: createGifAnim(URLS.ultimate_2_6, false),
      Ultimate_2_7: createGifAnim(URLS.ultimate_2_7, false),
      Ultimate_2_8: createGifAnim(URLS.ultimate_2_8, false),
      Ultimate_2_9: createGifAnim(URLS.ultimate_2_9, false),
      Ultimate_2_10: createGifAnim(URLS.ultimate_2_10, false),
      Ultimate_2_11: createGifAnim(URLS.ultimate_2_11, false),
      Ultimate_2_12: createGifAnim(URLS.ultimate_2_12, false),
      [PlayerState.STANDBY]: createGifAnim(URLS.parado, true),
      TAG_IN_KO: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_IN]: createGifAnim(URLS.entrada_por_ko, false),
      [PlayerState.TAG_OUT]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_ENTRY]: createGifAnim(URLS.parado, false),
      [PlayerState.ASSIST_EXIT]: createGifAnim(URLS.parado, false),
      [PlayerState.VICTORY]: createGifAnim(URLS.parado, false),
    }
  }
};
